### ISSUE TITLE
use web UI create hdfs sink connector, can't save data into hadoop

### ISSUE THREAD

**Issue by DavidMi-1** [oharastream/ohara#1036]
**Describe the bug**
俺使用網頁的 web UI 建立了一個 hdfs sink connector, 對 topic Isshin 裡的資料作處理要存進 hadoop, 有看到產生出資料夾路徑, 但是檔案沒有成功儲存進 hadoop hdfs

**To Reproduce**
1. Go to 'http://ohara-dev-00:5050/pipelines/edit'
2. Add topic -- Isshin
3. Add hdfs sink connector
4. setup  hdfs sink connector
5. start Operate
6. hadoop url -- hdfs://ohara-demo-cdh01:8020

**Expected behavior**
Isshin topic's data save into hadoop hdfs /data

**HDFS sink connector setup content**
Name：test_hdfs_isshin
Read topic：Isshin
Connection URL：hdfs://ohara-demo-cdh01:8020
Write path：/data
Temp directory：/tmp
File encoding：UTF-8
Rotate interval (ms)：60000
Flush line count：1

**k8s error log content**
[2019-05-06 03:54:11,075] INFO Kafka version : 1.0.2 (org.apache.kafka.common.utils.AppInfoParser:109)
[2019-05-06 03:54:11,075] INFO Kafka commitId : 2a121f7b1d402825 (org.apache.kafka.common.utils.AppInfoParser:110)
[2019-05-06 03:54:11,077] INFO Finished starting connectors and tasks (org.apache.kafka.connect.runtime.distributed.DistributedHerder:847)
[2019-05-06 03:54:11,078] INFO starting HDFS Sink Connector (com.island.ohara.connector.hdfs.HDFSSinkTask:56)
[2019-05-06 03:54:11,112] ERROR WorkerSinkTask{id=7e4314c3-4b29-4514-9e8d-f08b17f7cc5a-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:172)
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.island.ohara.connector.hdfs.DataWriter.<init>(DataWriter.scala:36)
	at com.island.ohara.connector.hdfs.HDFSSinkTask._start(HDFSSinkTask.scala:58)
	at com.island.ohara.kafka.connector.RowSinkTask.start(RowSinkTask.java:154)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:280)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:176)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: java.net.UnknownHostException: ohara-demo-cdh01
	at org.apache.hadoop.security.SecurityUtil.buildTokenService(SecurityUtil.java:378)
	at org.apache.hadoop.hdfs.NameNodeProxies.createNonHAProxy(NameNodeProxies.java:312)
	at org.apache.hadoop.hdfs.NameNodeProxies.createProxy(NameNodeProxies.java:178)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:677)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:619)
	at org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:149)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2653)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:92)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2687)
	at org.apache.hadoop.fs.FileSystem$Cache.getUnique(FileSystem.java:2675)
	at org.apache.hadoop.fs.FileSystem.newInstance(FileSystem.java:418)
	at com.island.ohara.connector.hdfs.creator.HDFSStorageCreator.<init>(HDFSStorageCreator.scala:32)
	... 16 more
Caused by: java.net.UnknownHostException: ohara-demo-cdh01
	... 28 more
[2019-05-06 03:54:11,112] ERROR WorkerSinkTask{id=7e4314c3-4b29-4514-9e8d-f08b17f7cc5a-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:173)
[2019-05-06 03:54:11,112] INFO running stop function (com.island.ohara.connector.hdfs.HDFSSinkTask:62)

**Operation System (please complete the following information):**
 - Backend OS & Version: [CentOS 7.2]
 - Frontend OS & Version: [CentOS 7.2]
 - Browser & Version [Chrome 74.0.3729.131]

**Comment by jackyoh** [comment]
UnknownHostException 的錯誤, 請參考 #1035 還要找時間, 去找問題在哪
