### ISSUE TITLE
Cannot run streamApp normally in pipeline

### ISSUE THREAD

**Issue by konekoya** [oharastream/ohara#1087]
**Describe the bug**
After starting a basic streamApp in pipeline page. StreamApp will be listed in the k8s console but with a wired error: __Back-off restarting failed container__

**To Reproduce**
This can be reproduced on demo env

- Navigate to http://10.2.0.24:5050
- Create a worker and a new pipeline
- Create two new topics from Service -> Broker page
- Add these two topics into the pipeline you just created and add a new streamApp as well
- Add necessary config for StreamApp
- Start the StreamApp. It should have not problem starting the StreamApp but the error will be shown on k8s console

**Expected behavior**
There shouldn't be any error when starting a StreamApp

**Screenshots**

**Operation System (please complete the following information):**
I'm using demo env...

**Additional context**
Actual error from k8s' log

```
Exception in thread "main" java.lang.IllegalArgumentException: /tmp/streamApp-4917433142574234469.jar exists
	at com.island.ohara.common.util.CommonUtils.requireNotExist(CommonUtils.java:542)
	at com.island.ohara.common.util.CommonUtils.copyURLToFile(CommonUtils.java:602)
	at com.island.ohara.streams.StreamApp.findStreamAppEntry(StreamApp.java:173)
	at com.island.ohara.streams.StreamApp.lambda$main$4(StreamApp.java:142)
	at com.island.ohara.kafka.exception.CheckedExceptionUtils.wrap(CheckedExceptionUtils.java:45)
	at com.island.ohara.streams.StreamApp.main(StreamApp.java:137)
```

**Comment by saivirtue** [comment]
Thanks @konekoya report this bug :)
