### ISSUE TITLE
JdbcSourceConnector fail in Oracle 

### ISSUE THREAD

**Issue by g1geordie** [oharastream/ohara#1096]
I use JDBCSourceConenctor in Oracle database .
There are a exception throw below 

```
 [2019-05-09 03:02:09,330] ERROR ORA-01000: maximum open cursors exceeded
 (com.island.ohara.connector.jdbc.source.JDBCSourceTask:98)
java.sql.SQLException: ORA-01000: maximum open cursors exceeded

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:494)
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:446)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1054)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:623)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:252)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:612)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:226)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:59)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:747)
	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:904)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1082)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3780)
	at oracle.jdbc.driver.T4CPreparedStatement.executeInternal(T4CPreparedStatement.java:1343)
	at oracle.jdbc.driver.OraclePreparedStatement.executeQuery(OraclePreparedStatement.java:3822)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeQuery(OraclePreparedStatementWrapper.java:1165)
	at oracle.jdbc.OracleDatabaseMetaData.getTables(OracleDatabaseMetaData.java:2721)
	at com.island.ohara.client.DatabaseClient$$anon$1.tables(DatabaseClient.scala:75)
	at com.island.ohara.connector.jdbc.source.DBTableDataProvider.columns(DBTableDataProvider.scala:48)
	at com.island.ohara.connector.jdbc.source.DBTableDataProvider.executeQuery(DBTableDataProvider.scala:35)
	at com.island.ohara.connector.jdbc.source.JDBCSourceTask._poll(JDBCSourceTask.scala:68)
	at com.island.ohara.kafka.connector.RowSourceTask.poll(RowSourceTask.java:101)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:204)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: Error : 1000, Position : 0, Sql = SELECT NULL AS table_cat,
       o.owner AS table_schem,
       o.object_name AS table_name,
       o.object_type AS table_type,
       NULL AS remarks
  FROM all_objects o
  WHERE o.owner LIKE :1 ESCAPE '/'
    AND o.object_name LIKE :2 ESCAPE '/'
    AND o.object_type IN ('TABLE', 'SYNONYM', 'VIEW')
  ORDER BY table_type, table_schem, table_name
, OriginalSql = SELECT NULL AS table_cat,
       o.owner AS table_schem,
       o.object_name AS table_name,
       o.object_type AS table_type,
       NULL AS remarks
  FROM all_objects o
  WHERE o.owner LIKE :1 ESCAPE '/'
    AND o.object_name LIKE :2 ESCAPE '/'
    AND o.object_type IN ('TABLE', 'SYNONYM', 'VIEW')
  ORDER BY table_type, table_schem, table_name
, Error Msg = ORA-01000: maximum open cursors exceeded

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:498)
	... 28 more
```
**Is it possible that con.getStatement is not close when statements execute throw an error**
```
DBTableDataProvider [39] :val preparedStatement: PreparedStatement = client.connection.prepareStatement(sql)
//where exception throw by 
DBTableDataProvider [44] :new QueryResultIterator(preparedStatement, columnNames)
```

**Comment by chia7712** [comment]
IIRC, the error you encountered yesterday is the driver is not loaded? Do you resolve the issue?

**Comment by g1geordie** [comment]
yes, 
The JdbcSourceConnector is work fine in PostgresSql now .

**Comment by chia7712** [comment]
Does the jar deployment of worker works well to you?

**Comment by g1geordie** [comment]
When I change to Oracle .
oracle connection is fine  . 
when I   with the wrong  setting  ,  "timestamp column name "
it throw errors   and the log quickly become mention above

**Comment by chia7712** [comment]
Seems this is related to #1089

**Comment by chia7712** [comment]
@jackyoh please take a look at this one? Have we resolved it?

**Comment by jackyoh** [comment]
這個議題和 #3125 是相關的，目前已經解決了。
