### ISSUE TITLE
[Question] I met a question about Connector API

### ISSUE THREAD

**Issue by g1geordie** [oharastream/ohara#1154]
I send a request to start the connector  with ohara-client.
then , there are 20% probability will fail.

I expect the start request will start the connect , no matter there are do async or not.
But there are no connector start .

Although I know this fail  is due to get worker info too long and response empty array. 

Stana wish it can be fix .

Here is faild msg:
```
java.lang.IllegalArgumentException: we can't choose default worker cluster since there is no worker cluster
	at com.island.ohara.client.HttpExecutor$HttpExecutorImpl.$anonfun$asError$1(HttpExecutor.scala:152)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at akka.http.scaladsl.util.FastFuture$.$anonfun$transformWith$1(FastFuture.scala:37)
	at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
	at akka.http.scaladsl.util.FastFuture$.transformWith$extension1(FastFuture.scala:45)
	at akka.http.scaladsl.util.FastFuture$.transformWith$extension0(FastFuture.scala:37)
	at akka.http.scaladsl.util.FastFuture$FulfilledFuture.transformWith(FastFuture.scala:86)
	at scala.concurrent.Future.flatMap(Future.scala:306)
	at scala.concurrent.Future.flatMap$(Future.scala:306)
	at akka.http.scaladsl.util.FastFuture$FulfilledFuture.flatMap(FastFuture.scala:77)
	at com.island.ohara.client.HttpExecutor$HttpExecutorImpl.asError(HttpExecutor.scala:148)
	at com.island.ohara.client.HttpExecutor$HttpExecutorImpl.unmarshal(HttpExecutor.scala:138)
	at com.island.ohara.client.HttpExecutor$HttpExecutorImpl.$anonfun$post$2(HttpExecutor.scala:183)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

```

**Comment by chia7712** [comment]
> I send a request to start the connector with ohara-client.

The error message seems is not related to ohara-client. Did you produce this error by Restful APIs?

**Comment by g1geordie** [comment]
sure , it's not related to ohara-client

**Comment by chia7712** [comment]
Are there any worker cluster existing in you ohara? The error is Ohara Configurator can’t find any running worker cluster.

**Comment by g1geordie** [comment]
我的意思是說 
我使用ohara-client 來送request .
我期望start connector 的request 可以啟動connector 
但有 20% 的機率  不會啟動 
我懷疑是  start connector 在找worker時  回傳了 []  所以 沒有worker 可以啟動 它就丟錯
它丟出的錯誤訊息在下面

**Comment by g1geordie** [comment]
worker  已經建立  
80% 的機率 會正常啟動 source 和 sink 在這個worker上面

**Comment by chia7712** [comment]
> 80% 的機率 會正常啟動 source 和 sink 在這個worker上面

seems a cache miss. Let me file a PR for it.

**Comment by g1geordie** [comment]
抱歉  我英文太菜

**Comment by vitojeng** [comment]
@g1geordie Thanks for the issue.

**Comment by chia7712** [comment]
@g1geordie Please close this issue if the latest of 0.4 works well for you.

**Comment by g1geordie** [comment]
Thanks  . work fine
