### ISSUE TITLE
Fix flaky TestDataTransmissionOnCluster.testRowProducer2RowConsumer

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#1176]
I've seen this error multiple times...so maybe it is time to dig it.

the full error trace :
```
org.scalatest.exceptions.TestFailedException: 0 was not equal to 20
	at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:346)
	at org.scalatest.Matchers$AnyShouldWrapper.shouldBe(Matchers.scala:6864)
	at com.island.ohara.client.kafka.TestDataTransmissionOnCluster.checkData(TestDataTransmissionOnCluster.scala:75)
	at com.island.ohara.client.kafka.TestDataTransmissionOnCluster.setupData(TestDataTransmissionOnCluster.scala:62)
	at com.island.ohara.client.kafka.TestDataTransmissionOnCluster.testRowProducer2RowConsumer(TestDataTransmissionOnCluster.scala:107)
	at com.island.ohara.client.kafka.TestDataTransmissionOnCluster.testRowProducer2RowConsumer(TestDataTransmissionOnCluster.scala:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by chia7712** [comment]
Reducing the number of tasks avoid the error on busy jenkins...
