### ISSUE TITLE
[Question] Unstable configurator in k8s environment

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#1371]
I am not very sure the problem is....so let me try to clarify the situation here.
The same problem occurs in our QA2 environment too, since it is the most recently commit from our master branch, maybe this problem is some time ago.

reproduce steps:
1. run configurator with pre-created clusters in k8s mode
1.1. --k8s
1.2. --node
2. create worker cluster
3. **important step** wait for a couple minutes, the configurator log will show something timeout message:
```
java.util.concurrent.TimeoutException: Futures timed out after [15 seconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:259)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:263)
	at scala.concurrent.Await$.$anonfun$result$1(package.scala:219)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:57)
	at scala.concurrent.Await$.result(package.scala:146)
	at com.island.ohara.configurator.Configurator.$anonfun$meterCache$7(Configurator.scala:141)
	at com.island.ohara.configurator.store.MeterCache$Builder$$anon$1.$anonfun$cache$1(MeterCache.scala:74)
	at com.island.ohara.common.cache.RefreshableCache$Builder.lambda$build$2(RefreshableCache.java:186)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

And for now on, the k8s environment becoming very slow:
- `kubectl` command will become very slow, even throw exception
- k8s proxy server will get some error message
`http: proxy error: context canceled`

The k8s will become stable after stop configurator

**Comment by saivirtue** [comment]
/cc @jackyoh 
根據剛剛討論，這個目前的解法可能有：
1. 將k8s取得clusters的動作cache，避免太常向k8s request
2. refactor目前的code，修改取得clusters的作法是所有的collie只會取一次，然後parser成各自collie的information

**Comment by jackyoh** [comment]
看起來是 k8s 的 api server 不能接受太頻繁的 request, 我覺得可以嘗試做 cache 的動作, 避免一直連到 k8s api server.

**Comment by saivirtue** [comment]
那再麻煩@jackyoh 開一個issue來refactor k8s cache，我這裡會持續找尋其他可行的方法

**Comment by jackyoh** [comment]
好, 我來開一個 issue 來 refactor k8s cache, 但是要到下一個 Milestone 才能做.

**Comment by vitojeng** [comment]
[這個文件](https://github.com/feiskyer/kubernetes-handbook/blob/master/practice/big-cluster.md#kube-apiserver-%E9%85%8D%E7%BD%AE) 提到的參數, 看看有沒有幫助

**Comment by saivirtue** [comment]
Since @jackyoh had created an issue to trace the problem, I will close this issue now.

**Comment by jackyoh** [comment]
目前測試覺得是 QA2 環境 K8S 版本的問題, 已經將 kubelet 從 v1.14.2 修改成 v1.14.1 了. @saivirtue 有空再幫我測看看是否還會出現相同的問題

**Comment by jackyoh** [comment]
#1422
