### ISSUE TITLE
[Question]Create a lot of topic then get topics failure

### ISSUE THREAD

**Issue by wu87988622** [oharastream/ohara#1429]
I create a lot of topic probably 24, then I use get topics api fail.

console:
`Jun 11, 2019 4:16:47 AM com.island.ohara.configurator.Configurator$$anonfun$exceptionHandler$1 $anonfun$applyOrElse$3
SEVERE: Request to http://10.1.13.100:12345/v0/topics with HttpEntity.Strict(application/json,{}) could not be handled normally
akka.stream.BufferOverflowException: Exceeded configured max-open-requests value of [256]. This means that the request queue of this pool (HostConnectionPoolSetup(10.1.13.100,8080,ConnectionPoolSetup(ConnectionPoolSettings(8,0,5,256,1,30 seconds,ClientConnectionSettings(Some(User-Agent: akka-http/10.1.3),10 seconds,1 minute,512,None,WebSocketSettings(<function0>,ping,Duration.Inf,akka.http.impl.settings.WebSocketSettingsImpl$$$Lambda$311/249177573@514b16c2),List(),ParserSettings(2048,16,64,64,8192,64,8388608,256,1048576,Strict,RFC6265,true,Set(),Full,Error,Map(If-Range -> 0, If-Modified-Since -> 0, If-Unmodified-Since -> 0, default -> 12, Content-MD5 -> 0, Date -> 0, If-Match -> 0, If-None-Match -> 0, User-Agent -> 32),false,true,akka.util.ConstantFun$$$Lambda$292/605101809@48bda02a,akka.util.ConstantFun$$$Lambda$292/605101809@48bda02a,akka.util.ConstantFun$$$Lambda$293/524223214@41c952f9),None,TCPTransport),New,1 second),akka.http.scaladsl.HttpConnectionContext$@60c7ec3a,akka.event.MarkerLoggingAdapter@2fcb3c7b))) has completely filled up because the pool currently does not process requests fast enough to handle the incoming request load. Please retry the request later. See http://doc.akka.io/docs/akka-http/current/scala/http/client-side/pool-overflow.html for more information.
	at akka.http.impl.engine.client.PoolInterfaceActor.<init>(PoolInterfaceActor.scala:88)
	at akka.http.impl.engine.client.PoolInterfaceActor$.$anonfun$props$1(PoolInterfaceActor.scala:34)
	at akka.actor.TypedCreatorFunctionConsumer.produce(IndirectActorProducer.scala:87)
	at akka.actor.Props.newActor(Props.scala:212)
	at akka.actor.ActorCell.newActor(ActorCell.scala:624)
	at akka.actor.ActorCell.create(ActorCell.scala:650)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:523)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:545)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:283)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)`

**Comment by chia7712** [comment]
Is there only a GET request? Or you re-submit many GET requests?

The GET /v0/obj is a expensive and slow operation, and it possibly make pool overload. There is already a issue trying to fix it (see #757)

**Comment by wu87988622** [comment]
> 是否只有GET請求？或者您重新提交了許多GET請求？
> 
> GET / v0 / obj是一個昂貴且緩慢的操作，它可能使池過載。試圖修復它已經存在問題（參見[＃757](https://github.com/oharastream/ohara/issues/757)）

only use get /v0/topics

I list all service for your reference, only topic fail.

Broker 1
Zookeeper 1
Worker 17
Topic 17
Node 18
Jar 17
