### ISSUE TITLE
Fix flaky Workers.fetchWorker and Workers.createWorker

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#1620]
```
錯誤訊息
expected undefined to be an array
堆疊追蹤
AssertionError: expected undefined to be an array
    at getRet (http://localhost:58730/__cypress/runner/cypress_runner.js:71699:16)
    at tryCatcher (http://localhost:58730/__cypress/runner/cypress_runner.js:132142:23)
    at Function.Promise.attempt.Promise.try (http://localhost:58730/__cypress/runner/cypress_runner.js:129516:29)
    at Context.thenFn (http://localhost:58730/__cypress/runner/cypress_runner.js:71713:26)
    at Context.then (http://localhost:58730/__cypress/runner/cypress_runner.js:71979:21)
    at Context.<anonymous> (http://localhost:58730/__cypress/runner/cypress_runner.js:79014:21)
    at http://localhost:58730/__cypress/runner/cypress_runner.js:78719:33
    at tryCatcher (http://localhost:58730/__cypress/runner/cypress_runner.js:132142:23)
    at Promise._settlePromiseFromHandler (http://localhost:58730/__cypress/runner/cypress_runner.js:130160:31)
    at Promise._settlePromise (http://localhost:58730/__cypress/runner/cypress_runner.js:130217:18)
    at Promise._settlePromiseCtx (http://localhost:58730/__cypress/runner/cypress_runner.js:130254:10)
    at Async._drainQueue (http://localhost:58730/__cypress/runner/cypress_runner.js:127071:12)
    at Async._drainQueues (http://localhost:58730/__cypress/runner/cypress_runner.js:127076:10)
    at Async.drainQueues (http://localhost:58730/__cypress/runner/cypress_runner.js:126950:14)
    at <anonymous>
```

```
錯誤訊息
expected false to equal true
堆疊追蹤
AssertionError: expected false to equal true
    at getRet (http://localhost:58730/__cypress/runner/cypress_runner.js:71699:16)
    at tryCatcher (http://localhost:58730/__cypress/runner/cypress_runner.js:132142:23)
    at Function.Promise.attempt.Promise.try (http://localhost:58730/__cypress/runner/cypress_runner.js:129516:29)
    at Context.thenFn (http://localhost:58730/__cypress/runner/cypress_runner.js:71713:26)
    at Context.then (http://localhost:58730/__cypress/runner/cypress_runner.js:71979:21)
    at Context.<anonymous> (http://localhost:58730/__cypress/runner/cypress_runner.js:79014:21)
    at http://localhost:58730/__cypress/runner/cypress_runner.js:78719:33
    at tryCatcher (http://localhost:58730/__cypress/runner/cypress_runner.js:132142:23)
    at Promise._settlePromiseFromHandler (http://localhost:58730/__cypress/runner/cypress_runner.js:130160:31)
    at Promise._settlePromise (http://localhost:58730/__cypress/runner/cypress_runner.js:130217:18)
    at Promise._settlePromiseCtx (http://localhost:58730/__cypress/runner/cypress_runner.js:130254:10)
    at Async._drainQueue (http://localhost:58730/__cypress/runner/cypress_runner.js:127071:12)
    at Async._drainQueues (http://localhost:58730/__cypress/runner/cypress_runner.js:127076:10)
    at Async.drainQueues (http://localhost:58730/__cypress/runner/cypress_runner.js:126950:14)
    at <anonymous>
```

[link](https://builds.is-land.com.tw/job/PreCommit-OHARA/3125/#showFailuresLink)

**Comment by chia7712** [comment]
from @wu87988622 

> This api test is fix in #1540
