### ISSUE TITLE
[Question] Connector error not shown in rest api response

### ISSUE THREAD

**Issue by alan791205** [oharastream/ohara#1786]
I am using postgres database as a source, 
and apparently some data types were not supported by ohara-stream connector so there will have some error messages inside worker like
```
[2019-07-09 07:25:55,711] ERROR Data type 'float8' not support on column 'air_delay'. (com.island.ohara.connector.jdbc.source.JDBCSourceTask:98)
java.lang.RuntimeException: Data type 'float8' not support on column 'air_delay'.
	at com.island.ohara.connector.jdbc.datatype.RDBDataTypeConverter.converterValue(RDBDataTypeConverter.scala:63)
	at com.island.ohara.connector.jdbc.source.ResultSetDataConverter$.$anonfun$converterRecord$1(ResultSetDataConverter.scala:39)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at scala.collection.TraversableLike.map(TraversableLike.scala:237)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:230)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at com.island.ohara.connector.jdbc.source.ResultSetDataConverter$.converterRecord(ResultSetDataConverter.scala:38)
	at com.island.ohara.connector.jdbc.source.QueryResultIterator.hasNext(QueryResultIterator.scala:37)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:489)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:62)
	at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:53)
	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:189)
	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:47)
	at scala.collection.TraversableOnce.to(TraversableOnce.scala:313)
	at scala.collection.TraversableOnce.to$(TraversableOnce.scala:311)
	at scala.collection.AbstractIterator.to(Iterator.scala:1429)
	at scala.collection.TraversableOnce.toList(TraversableOnce.scala:297)
	at scala.collection.TraversableOnce.toList$(TraversableOnce.scala:297)
	at scala.collection.AbstractIterator.toList(Iterator.scala:1429)
	at com.island.ohara.connector.jdbc.source.JDBCSourceTask._poll(JDBCSourceTask.scala:78)
	at com.island.ohara.kafka.connector.RowSourceTask.poll(RowSourceTask.java:101)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:245)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:221)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

So I tried to get more info calling get connector info by rest-api
(`curl http://$host/v0/connectors/$connectorid -X GET | jq`)
```
$ ./get_connector.sh 1f097574-ff0c-430c-a8a3-3391ec0ec31e
Get connector 1f097574-ff0c-430c-a8a3-3391ec0ec31e ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1234  100  1234    0     0  25708      0 --:--:-- --:--:-- --:--:-- 25708
{
  "topics": [
    "topic_fromFKiWrRv"
  ],
  "name": "postgresSQL",
  "state": "RUNNING",
  "lastModified": 1562657413570,
  "workerClusterName": "wk00",
  "configs": {
    "source.db.url": "jdbc:postgresql://xxx.xxx.xxx.xxx:5432/postgres",
    "name": "postgresSQL",
    "source.db.password": "xxxxxx",
    "workerClusterName": "wk00",
    "connector.class": "com.island.ohara.connector.jdbc.source.JDBCSourceConnector",
    "source.table.name": "flight_stat_100",
    "connector.name": "postgresSQL",
    "source.timestamp.column.name": "create_date",
    "source.db.username": "postgres"
  },
  "numberOfTasks": 1,
  "id": "1f097574-ff0c-430c-a8a3-3391ec0ec31e",
  "schema": [],
  "error": null,
  "className": "com.island.ohara.connector.jdbc.source.JDBCSourceConnector",
  "metrics": {
    "meters": [
      {
        "value": 0,
        "unit": "rows",
        "document": "number of rows"
      },
      {
        "value": 0,
        "unit": "bytes",
        "document": "size (in bytes) of rows"
      }
    ]
  },
  "settings": {
    "source.db.url": "jdbc:postgresql://xxx.xxx.xxx.xxx:5432/postgres",
    "topics": [
      "topic_fromFKiWrRv"
    ],
    "name": "postgresSQL",
    "source.db.password": "xxxxx",
    "workerClusterName": "wk00",
    "tasks.max": 1,
    "connector.class": "com.island.ohara.connector.jdbc.source.JDBCSourceConnector",
    "source.table.name": "flight_stat_100",
    "connector.name": "postgresSQL",
    "source.timestamp.column.name": "create_date",
    "source.db.username": "postgres"
  }
}
```

I did not see error messages shown inside column error.
Can I get this kind of error messages through rest-api or am I using the wrong API so I cannot get the error message?

**Comment by konekoya** [comment]
cc @oharastream/backend

**Comment by chia7712** [comment]
requesting Log API can retrieve the log details from the worker cluster. The state/error in Connector APIs can't give the full logs.

**Comment by chia7712** [comment]
@alan791205 Is this still available?
