### ISSUE TITLE
StreamApp could not parse url

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#2214]
When parsing streamApp definition from jar, the configurator will thrown
```
Exception in thread "main" com.island.ohara.common.exception.OharaException: java.net.MalformedURLException: no protocol: "http://XXXX/v0/downloadFiles/wk01/XXX.jar"
        at com.island.ohara.common.exception.ExceptionHandler$Builder$1.handle(ExceptionHandler.java:85)
        at com.island.ohara.streams.StreamApp.downloadJarByUrl(StreamApp.java:185)
        at com.island.ohara.streams.StreamApp.main(StreamApp.java:171)
Caused by: java.net.MalformedURLException: no protocol: "http://XXXX/v0/downloadFiles/wk01/XXX.jar"
        at java.net.URL.<init>(URL.java:600)
        at java.net.URL.<init>(URL.java:497)
        at java.net.URL.<init>(URL.java:446)
        at com.island.ohara.streams.StreamApp.lambda$downloadJarByUrl$2(StreamApp.java:186)
        at com.island.ohara.common.exception.ExceptionHandler$Builder$1.handle(ExceptionHandler.java:83)
        ... 2 more
```

**Comment by saivirtue** [comment]
thanks @konekoya !
