### ISSUE TITLE
FakeWorkerClient.localConnectorDefinitions should not instantiate the abstract classes 

### ISSUE THREAD

**Issue by eechih** [oharastream/ohara#2489]
2019-08-29 09:23:47,962 ERROR [main] fake.FakeWorkerClient$(145): failed to instantiate com.island.ohara.kafka.connector.csv.CsvSinkConnector for RowSourceConnector
java.lang.InstantiationException
	at sun.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(InstantiationExceptionConstructorAccessorImpl.java:48)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at com.island.ohara.configurator.fake.FakeWorkerClient$.$anonfun$localConnectorDefinitions$1(FakeWorkerClient.scala:142)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:245)
	at scala.collection.mutable.HashSet.foreach(HashSet.scala:79)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:245)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:242)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
	at com.island.ohara.configurator.fake.FakeWorkerClient$.localConnectorDefinitions$lzycompute(FakeWorkerClient.scala:141)
	at com.island.ohara.configurator.fake.FakeWorkerClient$.localConnectorDefinitions(FakeWorkerClient.scala:135)
	at com.island.ohara.configurator.ConfiguratorBuilder.$anonfun$fake$13(ConfiguratorBuilder.scala:281)
	at com.island.ohara.configurator.ConfiguratorBuilder.$anonfun$fake$13$adapted(ConfiguratorBuilder.scala:259)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
	at scala.collection.immutable.Range.foreach(Range.scala:158)
	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at com.island.ohara.configurator.ConfiguratorBuilder.$anonfun$fake$9(ConfiguratorBuilder.scala:259)
	at com.island.ohara.configurator.ConfiguratorBuilder.doOrReleaseObjects(ConfiguratorBuilder.scala:402)
	at com.island.ohara.configurator.ConfiguratorBuilder.fake(ConfiguratorBuilder.scala:204)
	at com.island.ohara.configurator.ConfiguratorBuilder.fake(ConfiguratorBuilder.scala:90)
	at com.island.ohara.configurator.route.TestStreamRoute.<init>(TestStreamRoute.scala:37)

**Comment by eechih** [comment]
Thanks to @saivirtue 's report

**Comment by chia7712** [comment]
@eechih Do you have free cycle to fix it? It is too noisy to me so I want to fix it ASAP :)

**Comment by eechih** [comment]
@chia7712 I'm Sorry! I don't have time to fix it now :(

**Comment by chia7712** [comment]
> I'm Sorry! I don't have time to fix it now :(

not a problem at all. Let me take over it :)
