### ISSUE TITLE
fix flaky IT tests TestXXXStreamApp.testDeadNodes

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#2549]
Reference Jenkins tasks: https://builds.is-land.com.tw/job/PreCommit-OHARA/5156/

TestXXXStreamApp.testDeadNodes
error message
```
java.lang.IllegalStateException: timeout
	at com.island.ohara.common.util.CommonUtils.await(CommonUtils.java:151)
	at com.island.ohara.common.util.CommonUtils.await(CommonUtils.java:119)
	at com.island.ohara.it.IntegrationTest$.await(IntegrationTest.scala:68)
	at com.island.ohara.it.IntegrationTest.await(IntegrationTest.scala:39)
	at com.island.ohara.it.agent.BasicTests4StreamApp.testDeadNodes(BasicTests4StreamApp.scala:409)
```

**Comment by chia7712** [comment]
this may be duplicate to #2475.

**Comment by chia7712** [comment]
BTW, there is a related issue (#2393)

**Comment by saivirtue** [comment]
Got it. Let me edit the description.

**Comment by saivirtue** [comment]
This issue is related to #2257 and should be resolved. Close this issue now.
