### ISSUE TITLE
[Question] Should we use the same rule for "hostname" in both docker and k8s?

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#2588]
In XXXCollieImpl, 

for docker
```
.hostname(containerInfo.hostname)
.envs(containerInfo.environments)
.name(containerInfo.name)
```

for k8s
```
.hostname(s"${containerInfo.name}$DIVIDER${node.name}")
.envs(containerInfo.environments)
.name(containerInfo.name)
```

1. Since **hostname** is used for communication between containers, we should use a unique name here.

2. The hostname for k8s is mapping to "spec.hostname", which has the following rules:
> Valid label values must be 63 characters or less and must be empty or begin and end with an alphanumeric character ([a-z0-9A-Z]) with dashes (-), underscores (_), dots (.), and alphanumerics between.

The hostname length should add a new rule that length < 63

**Comment by saivirtue** [comment]
ping @oharastream/developer 
any comment?

**Comment by chia7712** [comment]
the rule to hostname is ok to me but it is not critical. The hostname in container is private info and it is used by kafka/zk process only. Both Ohara and user DON'T touch the hostname in the later communication. It means the hostname is "create once, use nowhere".

**Comment by saivirtue** [comment]
> the rule to hostname is ok to me but it is not critical. 

I raise this issue because of the error in some of IT tests:
```
2019-09-08 14:36:16,044 INFO  [pool-1-thread-8] k8s.K8SClient$$anon$1$$anon$2(311): create pod request json: {"apiVersion":"v1","kind":"Pod","metadata":{"name":"k8soccl-default-pr2583125eb6b-stream-78af036","labels":{"name":"ohara"}},"spec":{"hostname":"k8soccl-default-pr2583125eb6b-stream-78af036-ohara-jenkins-it-12","hostAliases":[{"ip":"10.2.0.9","hostnames":["ohara-jenkins-it-10"]},{"ip":"10.2.0.10","hostnames":["ohara-jenkins-it-11"]},{"ip":"10.2.0.11","hostnames":["ohara-jenkins-it-12"]},{"ip":"10.2.0.10","hostnames":["ohara-jenkins-it-11"]},{"ip":"10.2.0.11","hostnames":["ohara-jenkins-it-12"]},{"ip":"10.1.0.100","hostnames":["ohara-jenkins-slave-00"]}],"subdomain":"default","nodeSelector":{"kubernetes.io/hostname":"ohara-jenkins-it-12"},"containers":[{"name":"ohara","image":"oharastream/streamapp:tmp_5259","ports":[{"containerPort":38083,"hostPort":38083}],"command":[],"args":["-Dcom.sun.management.jmxremote","-Dcom.sun.management.jmxremote.authenticate=false","-Dcom.sun.management.jmxremote.ssl=false","-Dcom.sun.management.jmxremote.port=38083","-Dcom.sun.management.jmxremote.rmi.port=38083","-Djava.rmi.server.hostname=ohara-jenkins-it-12","com.island.ohara.streams.StreamApp","jarUrl=http://ohara-jenkins-slave-00:16059/v0/downloadFiles/default/ohara-streamapp.jar"],"imagePullPolicy":"IfNotPresent","env":[{"name":"author","value":"jenkins"},{"name":"name","value":"pr2583125eb6b"},{"name":"exactlyOnce","value":"false"},{"name":"jarInfo","value":"{\\\"name\\\":\\\"ohara-streamapp.jar\\\",\\\"size\\\":1937,\\\"url\\\":\\\"http://ohara-jenkins-slave-00:16059/v0/downloadFiles/default/ohara-streamapp.jar\\\",\\\"lastModified\\\":1567953374000,\\\"tags\\\":{},\\\"group\\\":\\\"default\\\"}"},{"name":"streamMetricGroup","value":"streamapp"},{"name":"tags","value":"{}"},{"name":"imageName","value":"oharastream/streamapp:tmp_5259"},{"name":"jarKey","value":"{\\\"group\\\":\\\"default\\\",\\\"name\\\":\\\"ohara-streamapp.jar\\\"}"},{"name":"servers","value":"ohara-jenkins-it-11:46618"},{"name":"to","value":"[{\\\"group\\\":\\\"default\\\",\\\"name\\\":\\\"ffd0a\\\"}]"},{"name":"revision","value":"eed49c326f27ae1d61433e51e9b3227c3dac4f51"},{"name":"version","value":"tmp_5259"},{"name":"_key_to_settings_","value":"{\\\"author\\\":\\\"jenkins\\\",\\\"name\\\":\\\"pr2583125eb6b\\\",\\\"exactlyOnce\\\":\\\"false\\\",\\\"jarInfo\\\":{\\\"name\\\":\\\"ohara-streamapp.jar\\\",\\\"size\\\":1937,\\\"url\\\":\\\"http://ohara-jenkins-slave-00:16059/v0/downloadFiles/default/ohara-streamapp.jar\\\",\\\"lastModified\\\":1567953374000,\\\"tags\\\":{},\\\"group\\\":\\\"default\\\"},\\\"streamMetricGroup\\\":\\\"streamapp\\\",\\\"tags\\\":{},\\\"imageName\\\":\\\"oharastream/streamapp:tmp_5259\\\",\\\"jarKey\\\":{\\\"group\\\":\\\"default\\\",\\\"name\\\":\\\"ohara-streamapp.jar\\\"},\\\"servers\\\":\\\"ohara-jenkins-it-11:46618\\\",\\\"to\\\":[{\\\"group\\\":\\\"default\\\",\\\"name\\\":\\\"ffd0a\\\"}],\\\"revision\\\":\\\"eed49c326f27ae1d61433e51e9b3227c3dac4f51\\\",\\\"version\\\":\\\"tmp_5259\\\",\\\"from\\\":[{\\\"group\\\":\\\"default\\\",\\\"name\\\":\\\"359b2\\\"}],\\\"broker.cluster.name\\\":\\\"pr258356e1033\\\",\\\"jmxPort\\\":38083,\\\"nodeNames\\\":[\\\"ohara-jenkins-it-11\\\",\\\"ohara-jenkins-it-12\\\"]}"},{"name":"from","value":"[{\\\"group\\\":\\\"default\\\",\\\"name\\\":\\\"359b2\\\"}]"},{"name":"broker.cluster.name","value":"pr258356e1033"},{"name":"jmxPort","value":"38083"},{"name":"nodeNames","value":"[\\\"ohara-jenkins-it-11\\\",\\\"ohara-jenkins-it-12\\\"]"}]}],"restartPolicy":"Never"}}
2019-09-08 14:36:16,051 ERROR [pool-1-thread-3] k8s.K8SStreamCollieImpl$$anonfun$doCreator$1(61): failed to start oharastream/streamapp:tmp_5259 on ohara-jenkins-it-12
java.lang.RuntimeException: Pod "k8soccl-default-pr2583125eb6b-stream-78af036" is invalid: spec.hostname: Invalid value: "k8soccl-default-pr2583125eb6b-stream-78af036-ohara-jenkins-it-12": must be no more than 63 characters
	at com.island.ohara.agent.k8s.K8SClient$$anon$1.$anonfun$unmarshal$1(K8SClient.scala:369)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at akka.http.scaladsl.util.FastFuture$.$anonfun$transformWith$1(FastFuture.scala:37)
	at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
	at akka.http.scaladsl.util.FastFuture$.transformWith$extension1(FastFuture.scala:45)
	at akka.http.scaladsl.util.FastFuture$.transformWith$extension0(FastFuture.scala:37)
	at akka.http.scaladsl.util.FastFuture$FulfilledFuture.transformWith(FastFuture.scala:86)
	at scala.concurrent.Future.flatMap(Future.scala:306)
	at scala.concurrent.Future.flatMap$(Future.scala:306)
	at akka.http.scaladsl.util.FastFuture$FulfilledFuture.flatMap(FastFuture.scala:77)
	at com.island.ohara.agent.k8s.K8SClient$$anon$1.com$island$ohara$agent$k8s$K8SClient$$anon$$unmarshal(K8SClient.scala:368)
	at com.island.ohara.agent.k8s.K8SClient$$anon$1$$anon$2.$anonfun$create$7(K8SClient.scala:317)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
Although it is just the label length limit issue, I hope someone won't face the same problem if they had changed the container creation impl later.
Adding the rules before actual creation could help the error fail-fast.

**Comment by chia7712** [comment]
go ahead to file PR to fix this issue if it indeed is a bug to our code.

my point was that we don't need to have a rule to all collie impl since it is not such public stuff.

**Comment by saivirtue** [comment]
Since the failed IT tests (in #2583) only occur in stream collie, I prefer to the point that we should only change the issue part, not all collie stuff. This issue should be closed since the other part is not critical.
