### ISSUE TITLE
Failed to test com.island.ohara.client.kafka.TestWorkerClient.testAllPluginDefinitions() when depends on ohara-kafka

### ISSUE THREAD

**Issue by eechih** [oharastream/ohara#2605]
If the ohara-client module depends on ohara-kafka test code, the test com.island.ohara.client.kafka.TestWorkerClient.testAllPluginDefinitions() will not pass. 

build.gradle:
```
testImplementation project(":ohara-kafka").sourceSets.test.output
```
Test Results:
```
org.scalatest.exceptions.TestFailedException: 0 was equal to 0
	at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:346)
	at org.scalatest.words.ResultOfNotWordForAny.be(ResultOfNotWordForAny.scala:85)
	at com.island.ohara.client.kafka.TestWorkerClient.testAllPluginDefinitions(TestWorkerClient.scala:179)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by chia7712** [comment]
interesting ...
