### ISSUE TITLE
Fix flaky TestK8SSimpleCollie

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara#2667]
目前 TestK8SSimpleCollie 整合測試有以下幾隻 function 是失敗的狀態，需要做修改：
testWorker
testAddBrokerNode
testAddWorkerNode

the root cause is that we do a full string comparison in multiple nodes. And the order of nodes is not fixed so it has chance to produce false result.

log:
```
錯誤訊息
org.scalatest.exceptions.TestFailedException: "ohara-jenkins-it-1[0:45969,ohara-jenkins-it-11]:45969" was not equal to "ohara-jenkins-it-1[1:45969,ohara-jenkins-it-10]:45969"
堆疊追蹤
org.scalatest.exceptions.TestFailedException: "ohara-jenkins-it-1[0:45969,ohara-jenkins-it-11]:45969" was not equal to "ohara-jenkins-it-1[1:45969,ohara-jenkins-it-10]:45969"
	at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:346)
	at org.scalatest.Matchers$AnyShouldWrapper.shouldBe(Matchers.scala:6864)
	at com.island.ohara.it.agent.k8s.TestK8SSimpleCollie.testAddBrokerNode(TestK8SSimpleCollie.scala:247)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

```
錯誤訊息
org.scalatest.exceptions.TestFailedException: false was not equal to true
堆疊追蹤
org.scalatest.exceptions.TestFailedException: false was not equal to true
	at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:346)
	at org.scalatest.Matchers$AnyShouldWrapper.shouldBe(Matchers.scala:6864)
	at com.island.ohara.it.agent.k8s.TestK8SSimpleCollie.testAddWorkerNode(TestK8SSimpleCollie.scala:296)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by chia7712** [comment]
@jackyoh Let me take over this one to make QA green ASAP.

**Comment by jackyoh** [comment]
@chia7712 Thank you!

**Comment by jackyoh** [comment]
整合測試還有一個地方有問題。TestK8sClusterCollie#testWorker 測試，在 cluster00 的 IT 跑會順利通過，但是使用 cluster10 的 IT 跑在  testRemoveNodeToRunningWorkerCluster 的方法會卡在這個方法的 await 裡面。這個問題很像之前發生的跟 k8s 啟動 broker 的順序有關，我再找 @chia7712 討論看看。在決定是否要開 issue
