### ISSUE TITLE
執行 Configurator 的 container 使用 -v 發生 Permission denied 的問題

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara#2778]
今天在寫文章的時候，使用 Ohara 0.7.1 的 Quick Start VM 測試關於 Rocks DB 的資料夾 mapping 到 container 的資料夾時發現有 Permission denied 的問題，指令如下:

```
$ docker run -v /tmp/configurator:/home/ohara/configurator -p 12345:12345 oharastream/configurator:0.7.1 --port 12345 --folder /home/ohara/configurator
```

2019-09-25 02:15:05,702 ERROR [main] configurator.ConfiguratorBuilder(405): failed to pre-create resource
org.rocksdb.RocksDBException: while open a file for lock: /home/ohara/configurator/store/LOCK: Permission denied
	at org.rocksdb.RocksDB.open(Native Method)
	at org.rocksdb.RocksDB.open(RocksDB.java:286)
	at com.island.ohara.configurator.store.RocksDataStore.<init>(RocksDataStore.scala:85)
	at com.island.ohara.configurator.store.DataStore$Builder.build(DataStore.scala:166)
	at com.island.ohara.configurator.ConfiguratorBuilder.getOrCreateStore(ConfiguratorBuilder.scala:375)
	at com.island.ohara.configurator.ConfiguratorBuilder.$anonfun$build$1(ConfiguratorBuilder.scala:350)
	at com.island.ohara.configurator.ConfiguratorBuilder.doOrReleaseObjects(ConfiguratorBuilder.scala:402)
	at com.island.ohara.configurator.ConfiguratorBuilder.build(ConfiguratorBuilder.scala:350)
	at com.island.ohara.configurator.Configurator$.configurator(Configurator.scala:330)
	at com.island.ohara.configurator.Configurator$.main(Configurator.scala:346)
	at com.island.ohara.configurator.Configurator.main(Configurator.scala)
Exception in thread "main" org.rocksdb.RocksDBException: while open a file for lock: /home/ohara/configurator/store/LOCK: Permission denied
	at org.rocksdb.RocksDB.open(Native Method)
	at org.rocksdb.RocksDB.open(RocksDB.java:286)
	at com.island.ohara.configurator.store.RocksDataStore.<init>(RocksDataStore.scala:85)
	at com.island.ohara.configurator.store.DataStore$Builder.build(DataStore.scala:166)
	at com.island.ohara.configurator.ConfiguratorBuilder.getOrCreateStore(ConfiguratorBuilder.scala:375)
	at com.island.ohara.configurator.ConfiguratorBuilder.$anonfun$build$1(ConfiguratorBuilder.scala:350)
	at com.island.ohara.configurator.ConfiguratorBuilder.doOrReleaseObjects(ConfiguratorBuilder.scala:402)
	at com.island.ohara.configurator.ConfiguratorBuilder.build(ConfiguratorBuilder.scala:350)
	at com.island.ohara.configurator.Configurator$.configurator(Configurator.scala:330)
	at com.island.ohara.configurator.Configurator$.main(Configurator.scala:346)
	at com.island.ohara.configurator.Configurator.main(Configurator.scala)

加上 -u root 參數之後 configurator 的 container 就可以啟動，不太確定是否是 docker container 的問題。我之後會去研究看看

**Comment by saivirtue** [comment]
這個議題看起來跟 #2573 有關

**Comment by jackyoh** [comment]
了解，看起來是 UID 的問題。我先把這個 issue 關閉

**Comment by chia7712** [comment]
yep, uid is the root cause.
