### ISSUE TITLE
fix TestSshOracleJDBCSourceConnector

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#2818]
```
錯誤訊息
java.lang.IllegalArgumentException: 
堆疊追蹤
java.lang.IllegalArgumentException: 
	at com.island.ohara.common.util.CommonUtils.requireNonEmpty(CommonUtils.java:365)
	at com.island.ohara.common.util.CommonUtils.requireNonEmpty(CommonUtils.java:400)
	at com.island.ohara.client.kafka.WorkerClient$Builder.connectionProps(WorkerClient.scala:209)
	at com.island.ohara.client.kafka.WorkerClient$.apply(WorkerClient.scala:197)
	at com.island.ohara.it.connector.BasicTestConnectorCollie.runningJDBCSourceConnector(BasicTestConnectorCollie.scala:183)
	at com.island.ohara.it.connector.BasicTestConnectorCollie.testJDBCSourceConnector(BasicTestConnectorCollie.scala:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

the connection props is made up of "alive" nodes rather than node names. Hence, the "non-running" cluster returns empty string and it causes a lot of exception.

Given that the connection error should be handled by client code, the connection props, now, consists of all node names.

**Comment by jackyoh** [comment]
@chia7712 Thank you.
