### ISSUE TITLE
Added time frequence argument and close PreparedStatement for JDBC source connector

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara#3125]
JDBC Source Connector 查詢資料的 executeQuery 是寫在 _poll 的方法裡，我們無法預期 _poll 方法何時被呼叫，如果一直呼叫 _poll 方法，就會一直執行 executeQuery 造成資料庫的負擔，像是 Oracle database 就會丟出以下的錯誤訊息:
```
[2019-10-29 08:38:12,000] ERROR ORA-01000: maximum open cursors exceeded
 (com.island.ohara.connector.jdbc.source.JDBCSourceTask:119)
java.sql.SQLException: ORA-01000: maximum open cursors exceeded

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:494)
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:446)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1054)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:623)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:252)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:612)
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:213)
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:37)
	at oracle.jdbc.driver.T4CStatement.executeForDescribe(T4CStatement.java:733)
	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:904)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1082)
	at oracle.jdbc.driver.OracleStatement.executeQuery(OracleStatement.java:1276)
	at oracle.jdbc.driver.OracleStatementWrapper.executeQuery(OracleStatementWrapper.java:366)
```
以上的錯誤主要是太頻繁的執行 executeQuery 產生的 ResultSet 數量大於 oracle database 的 cursors 數量，要解決此問題需要做以下幾個項目：
- [ ] 確實檢查 PreparedStatement 是否有被 close 掉
- [x] 增加一個時間區間的參數，每隔一定的秒數到了才去資料庫拉資料，避免很快速的去執行 executeQuery

**Comment by chia7712** [comment]
> 增加一個時間區間的參數，每隔一定的秒數到了才去資料庫拉資料，避免很快速的去執行

This argument should be none by default. The throttle does impact performance ...

**Comment by jackyoh** [comment]
> This argument should be none by default

這個 default 的意思是指實做的參數預設值為 None 嗎？

**Comment by chia7712** [comment]
>這個 default 的意思是指實做的參數預設值為 None 嗎？

yep

**Comment by jackyoh** [comment]
紀錄調 oracle 的 cursor 的方式
進入 sqlplus 的 command line 輸入以下的指令
```
show parameter open_cursors;
alter system set open_cursors=1000 scope=both;
```
