### ISSUE TITLE
使用RESTAPI啟動ZKCluster與BKCluster失敗

### ISSUE THREAD

**Issue by HarryChiang143** [oharastream/ohara#318]
**Description:**
今天我嘗試使用Docker hub上下載的Docker image啟動完Ohara-configurator 以及 Ohara-manager並利用UI新增Ohara-nodes之後，嘗試透過RESTAPI去啟動ZKCluster及BKCluster均出現問題。
**### TestScenario1:**
我透過Docker-compose up 啟動configurator 及 manager的file 資訊
<img width="611" alt="2019-02-22 5 40 02" src="https://user-images.githubusercontent.com/46185836/53233719-00210080-36c9-11e9-9892-a8c0527bb4bf.png">

在UI上新增的ohara-node資訊(帶Hostname)
![2019-02-22 5 39 47](https://user-images.githubusercontent.com/46185836/53233683-ef708a80-36c8-11e9-851c-111a1c634890.png)

透過REST去啟動ZKCluster失敗
![2019-02-22 5 41 33](https://user-images.githubusercontent.com/46185836/53233790-2b0b5480-36c9-11e9-9737-415446e59775.png)

log:
configurator_1  |   "name": "zkcluster1",
configurator_1  |   "nodeNames": [
configurator_1  |     "slave4","tf-master1","worker1"
configurator_1  |   ]
configurator_1  | }
configurator_1  | ) is wrong
configurator_1  | java.lang.IllegalArgumentException: failed to create zkcluster1 on zk
configurator_1  | 	at com.island.ohara.agent.ClusterCollieImpl$ZookeeperCollieImpl.$anonfun$creator$5(ClusterCollieImpl.scala:369)
configurator_1  | 	at scala.util.Success.$anonfun$map$1(Try.scala:255)
configurator_1  | 	at scala.util.Success.map(Try.scala:213)
configurator_1  | 	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
configurator_1  | 	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
configurator_1  | 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
configurator_1  | 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
configurator_1  | 	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
configurator_1  | 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
configurator_1  | 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
configurator_1  | 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
configurator_1  | 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**### TestScenario2:**
我透過Docker-compose up 啟動configurator 及 manager的file 資訊
<img width="611" alt="2019-02-22 5 40 02" src="https://user-images.githubusercontent.com/46185836/53233719-00210080-36c9-11e9-9892-a8c0527bb4bf.png">

在UI上新增的ohara-node資訊(改成帶IP)
![2019-02-22 5 45 01](https://user-images.githubusercontent.com/46185836/53234055-aa992380-36c9-11e9-9385-277cb5717f74.png)

透過REST去啟動ZKCluster反而成功！
![2019-02-22 5 46 36](https://user-images.githubusercontent.com/46185836/53234135-d61c0e00-36c9-11e9-9063-d3da230f64d9.png)

接著透過REST去啟動BKCluster，看起來有建立成功，但是過一下子就掛了
![2019-02-22 5 47 36](https://user-images.githubusercontent.com/46185836/53234190-f5b33680-36c9-11e9-8a3a-c0fb0e4d1ade.png)
![2019-02-22 5 49 14](https://user-images.githubusercontent.com/46185836/53234311-3c089580-36ca-11e9-8fc1-131af4f168b7.png)

附檔是我運行configurator的log
[configurator-log.txt](https://github.com/oharastream/ohara/files/2893341/configurator-log.txt)

 剛剛有先請@Chia-Ping Tsai 看了一下broker裡面的log，似乎是跟Zookeeper連線打不到導致Timeout。

**My testEnv info:**
OS：CentOS Linux release 7.5.1804 (Core)
Java Version : Java 1.8(oracle jdk 8u161)
Docker Version：18.09.2
Security：none

TestHost: 
slave4 192.168.57.106
tf-master1 192.168.57.111
worker1 192.168.57.131 (目前所有啟動的服務都在這台上，包含manager、configurator、ZK、BK)

**Comment by HarryChiang143** [comment]
v0.2 的 bug 都會在 jira 去建立
