### ISSUE TITLE
研究 k8sConfigurator 跑整合測試常出現 timeout exception

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara#3301]
在執行整合測試時 k8sConfigurator 常出現 timeout exception, 最主要是 TestK8SStream.testDeadNodes 和 TestK8SCollie.testBroker 這二個測試方法常出現錯誤

TestK8SCollie.testBroker
```
java.lang.IllegalStateException: timeout
	at com.island.ohara.common.util.CommonUtils.await(CommonUtils.java:158)
	at com.island.ohara.common.util.CommonUtils.await(CommonUtils.java:126)
	at com.island.ohara.it.IntegrationTest$.await(IntegrationTest.scala:89)
	at com.island.ohara.it.IntegrationTest.await(IntegrationTest.scala:45)
	at com.island.ohara.it.agent.BasicTests4Collie.testRemoveNodeToRunningBrokerCluster(BasicTests4Collie.scala:462)
	at com.island.ohara.it.agent.BasicTests4Collie.testBroker(BasicTests4Collie.scala:345)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

TestK8SStream.testDeadNodes
```
org.scalatest.exceptions.TestFailedException: Set("ohara-jenkins-it-02") was not equal to Set()
	at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:346)
	at org.scalatest.Matchers$AnyShouldWrapper.shouldBe(Matchers.scala:6864)
	at com.island.ohara.it.agent.BasicTests4Stream.testDeadNodes(BasicTests4Stream.scala:275)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by jackyoh** [comment]
目前有找到問題在 issue #3325，我先把此議題關閉。
