### ISSUE TITLE
fix flaky TestConfigurator.testK8SNodes

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#3428]
```
java.lang.IllegalStateException: (default, node1} already exists on com.island.ohara.client.configurator.v0.NodeApi$Node
	at com.island.ohara.configurator.store.RocksDataStore.addIfAbsent(RocksDataStore.scala:187)
	at com.island.ohara.configurator.route.RouteBuilder$.$anonfun$apply$10(RouteBuilder.scala:209)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

our loop of updating k8s node does not skip the existent nodes ...

1. - [x] fix flaky TestConfigurator.testK8SNodes (#3529)
1. - [x] swallow the exception generated by addK8SNodes since the data conflict is fine (#3549)

**Comment by chia7712** [comment]
FYI @jackyoh

**Comment by jackyoh** [comment]
OK, 收到。這個問題常發生在整合測試的錯誤，我再找時間來解這個問題。

**Comment by chia7712** [comment]
```
2019-12-16 23:36:15,802 ERROR [Configurator-system-akka.actor.default-dispatcher-9] configurator.Configurator$$anonfun$exceptionHandler$1(140): Request to http://node00:45652/v0/nodes with HttpEntity.Strict(application/json,{"hostname":"node3","port":22,"tags":{}}) could not be handled normally
java.lang.IllegalStateException: (default, node3} already exists on com.island.ohara.client.configurator.v0.NodeApi$Node
	at com.island.ohara.configurator.store.RocksDataStore.addIfAbsent(RocksDataStore.scala:187)
	at com.island.ohara.configurator.route.RouteBuilder$.$anonfun$apply$10(RouteBuilder.scala:209)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
