### ISSUE TITLE
Run performance test failed

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara#3447]
目前在執行 performance test 時會出現以下的錯誤訊息：
```
spray.json.DeserializationException: Object is missing required member 'name'
	at spray.json.package$.deserializationError(package.scala:23)
	at spray.json.ProductFormats.fromField(ProductFormats.scala:62)
	at spray.json.ProductFormats.fromField$(ProductFormats.scala:50)
	at spray.json.DefaultJsonProtocol$.fromField(DefaultJsonProtocol.scala:30)
	at spray.json.ProductFormatsInstances$$anon$5.read(ProductFormatsInstances.scala:133)
	at spray.json.ProductFormatsInstances$$anon$5.read(ProductFormatsInstances.scala:118)
	at com.island.ohara.client.configurator.v0.ConnectorApi$$anon$4.read(ConnectorApi.scala:215)
	at com.island.ohara.client.configurator.v0.ConnectorApi$$anon$4.read(ConnectorApi.scala:213)
	at spray.json.JsValue.convertTo(JsValue.scala:32)
	at spray.json.CollectionFormats$$anon$4.$anonfun$read$4(CollectionFormats.scala:89)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at spray.json.CollectionFormats$$anon$4.read(CollectionFormats.scala:89)
	at spray.json.CollectionFormats$$anon$4.read(CollectionFormats.scala:86)
	at akka.http.scaladsl.marshallers.sprayjson.SprayJsonSupport.$anonfun$sprayJsonUnmarshaller$1(SprayJsonSupport.scala:30)
	at akka.http.scaladsl.util.FastFuture$.$anonfun$map$1(FastFuture.scala:23)
	at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
	at akka.http.scaladsl.util.FastFuture$.transformWith$extension1(FastFuture.scala:45)
	at akka.http.scaladsl.util.FastFuture$.map$extension(FastFuture.scala:23)
	at akka.http.scaladsl.unmarshalling.Unmarshaller.$anonfun$map$3(Unmarshaller.scala:26)
	at akka.http.scaladsl.unmarshalling.Unmarshaller.$anonfun$transform$3(Unmarshaller.scala:23)
	at akka.http.scaladsl.unmarshalling.Unmarshaller$$anon$1.apply(Unmarshaller.scala:58)
	at akka.http.scaladsl.unmarshalling.Unmarshal.to(Unmarshal.scala:25)
	at com.island.ohara.client.HttpExecutor$HttpExecutorImpl.unmarshal(HttpExecutor.scala:141)
	at com.island.ohara.client.HttpExecutor$HttpExecutorImpl.$anonfun$get$1(HttpExecutor.scala:179)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.util.NoSuchElementException: key not found: name
	at scala.collection.MapLike.default(MapLike.scala:235)
	at scala.collection.MapLike.default$(MapLike.scala:234)
	at scala.collection.AbstractMap.default(Map.scala:63)
	at scala.collection.MapLike.apply(MapLike.scala:144)
	at scala.collection.MapLike.apply$(MapLike.scala:143)
	at scala.collection.AbstractMap.apply(Map.scala:63)
	at spray.json.ProductFormats.fromField(ProductFormats.scala:57)
	at spray.json.ProductFormats.fromField$(ProductFormats.scala:50)
```

使用的指令如下
```
gradle clean ohara-it:test --tests TestPerformance4JsonOut -Pohara.it.docker=oooo:xxxx@hostname:22 -PskipManager
```

**Comment by jackyoh** [comment]
configurator 的 docker image 我忘了更新，更新完成 configurator 的 docker image 就可以順利執行了。
