### ISSUE TITLE
configurator 錯誤訊息有可能將 node 的密碼印出

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara#3534]
如果發生 exception 有可能將 node 的密碼印出, log 訊息如下：
```
2019-12-13 03:26:57,661 ERROR [Configurator-system-akka.actor.default-dispatcher-6] configurator.Configurator$$anonfun$exceptionHandler$1(140): Request to http://ohara-jenkins-it-00:33789/v0/nodes with HttpEntity.Strict(application/json,{"hostname":"ohara-jenkins-it-01","tags":{},"port":22,"user":"","password":""}) could not be handled normally
java.net.ConnectException: Connection refused
	at sun.nio.ch.UnixAsynchronousSocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.UnixAsynchronousSocketChannelImpl.finishConnect(UnixAsynchronousSocketChannelImpl.java:252)
	at sun.nio.ch.UnixAsynchronousSocketChannelImpl.finish(UnixAsynchronousSocketChannelImpl.java:198)
	at sun.nio.ch.UnixAsynchronousSocketChannelImpl.onEvent(UnixAsynchronousSocketChannelImpl.java:213)
	at sun.nio.ch.EPollPort$EventHandlerTask.run(EPollPort.java:293)
```

**Comment by chia7712** [comment]
@jackyoh nice finding

**Comment by jackyoh** [comment]
Thank you. 我把這個 issue assignees 給我
