### ISSUE TITLE
fix flaky TestErrorMessageOfConnector.succeedToRun

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#3570]
```
2019-12-18T10:59:00.4491694Z com.island.ohara.configurator.TestErrorMessageOfConnector > succeedToRun FAILED
2019-12-18T10:59:00.4492120Z     org.scalatest.exceptions.TestFailedException: UNASSIGNED was not equal to RUNNING
2019-12-18T10:59:00.4492555Z         at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:346)
2019-12-18T10:59:00.4492950Z         at org.scalatest.Matchers$AnyShouldWrapper.shouldBe(Matchers.scala:6864)
2019-12-18T10:59:00.4493335Z         at com.island.ohara.configurator.TestErrorMessageOfConnector.succeedToRun(TestErrorMessageOfConnector.scala:130)
```

**Comment by saivirtue** [comment]
Will this issue merge to `0.9` before today noon?
If not, please help me to move this issue to `0.10` :)
