### ISSUE TITLE
[Question] 建立 broker container 收到 Connection refused to host: 的 error 訊息

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara#3653]
使用 configurator 建立 broker container service 時，在 configurator 的 log 會收到以下 error 訊息，但 broker container service 有成功被建立起來。看起來是非同步的問題造成，不太確定這個問題是否有解？

```
2019-12-31 14:23:45,592 INFO  [main] configurator.Configurator$(393): enter ctrl+c to terminate the configurator
2019-12-31 14:25:11,291 ERROR [pool-1-thread-2] configurator.Configurator$$anonfun$$nestedInanonfun$meterCache$1$1(169): failed to get metrics of service:{"group":"default","name":"bk"} from $anon$2
java.lang.IllegalArgumentException: java.io.IOException: Failed to retrieve RMIServer stub: javax.naming.ServiceUnavailableException [Root exception is java.rmi.ConnectException: Connection refused to host: ohara-jenkins-it-01; nested exception is: 
	java.net.ConnectException: 連線被拒絕 (Connection refused)]
	at com.island.ohara.metrics.BeanChannel$Builder.doBuild(BeanChannel.java:321)
	at com.island.ohara.metrics.BeanChannel$Builder.build(BeanChannel.java:329)
	at com.island.ohara.agent.Collie.$anonfun$topicMeters$1(Collie.scala:251)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:245)
	at scala.collection.immutable.Set$Set1.foreach(Set.scala:97)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:245)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:242)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
	at com.island.ohara.agent.Collie.topicMeters(Collie.scala:250)
	at com.island.ohara.agent.Collie.topicMeters$(Collie.scala:248)
	at com.island.ohara.agent.k8s.K8SBasicCollieImpl.topicMeters(K8SBasicCollieImpl.scala:28)
	at com.island.ohara.agent.Collie.$anonfun$counters$6(Collie.scala:299)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Failed to retrieve RMIServer stub: javax.naming.ServiceUnavailableException [Root exception is java.rmi.ConnectException: Connection refused to host: ohara-jenkins-it-01; nested exception is: 
	java.net.ConnectException: 連線被拒絕 (Connection refused)]
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:369)
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270)
	at com.island.ohara.metrics.BeanChannel$Builder.doBuild(BeanChannel.java:281)
	... 20 more
Caused by: javax.naming.ServiceUnavailableException [Root exception is java.rmi.ConnectException: Connection refused to host: ohara-jenkins-it-01; nested exception is: 
	java.net.ConnectException: 連線被拒絕 (Connection refused)]
	at com.sun.jndi.rmi.registry.RegistryContext.lookup(RegistryContext.java:136)
	at com.sun.jndi.toolkit.url.GenericURLContext.lookup(GenericURLContext.java:205)
	at javax.naming.InitialContext.lookup(InitialContext.java:417)
	at javax.management.remote.rmi.RMIConnector.findRMIServerJNDI(RMIConnector.java:1955)
	at javax.management.remote.rmi.RMIConnector.findRMIServer(RMIConnector.java:1922)
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:287)
	... 22 more
```

**Comment by vitojeng** [comment]
我用 intellij 啟動 Configurator 時也有撞到這個 issue, 但不是每次都有. 是否可以視為正常情形?

**Comment by chia7712** [comment]
我剛剛測了最新的images，開了三個topics和三個connectors，在我的vms上只有一開始會噴出metrics timeout。
