### ISSUE TITLE
TestPerformance4PerfSource 在執行測試時出現 error

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara#3665]
目前在使用 TestPerformance4PerfSource 執行測試時會出現以下的錯誤訊息：
```
java.lang.IllegalArgumentException: The http server closed the connection unexpectedly before delivering responses for 1 outstanding requests
	at com.island.ohara.client.HttpExecutor$HttpExecutorImpl.$anonfun$asError$1(HttpExecutor.scala:164)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at akka.http.scaladsl.util.FastFuture$.$anonfun$transformWith$1(FastFuture.scala:37)
	at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
	at akka.http.scaladsl.util.FastFuture$.transformWith$extension1(FastFuture.scala:45)
	at akka.http.scaladsl.util.FastFuture$.transformWith$extension0(FastFuture.scala:37)
	at akka.http.scaladsl.util.FastFuture$FulfilledFuture.transformWith(FastFuture.scala:86)
	at scala.concurrent.Future.flatMap(Future.scala:306)
	at scala.concurrent.Future.flatMap$(Future.scala:306)
	at akka.http.scaladsl.util.FastFuture$FulfilledFuture.flatMap(FastFuture.scala:77)
	at com.island.ohara.client.HttpExecutor$HttpExecutorImpl.asError(HttpExecutor.scala:160)
	at com.island.ohara.client.HttpExecutor$HttpExecutorImpl.unmarshal(HttpExecutor.scala:142)
	at com.island.ohara.client.HttpExecutor$HttpExecutorImpl.$anonfun$post$2(HttpExecutor.scala:201)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```
ping @chia7712 我找很久找不出原因, 幫我看ㄧ下。我來修改

**Comment by jackyoh** [comment]
目前有找到一個簡單的解決方法, 在 WithRemoteWorkers.scala 的 setupWorkers 方法的最後一行加上

```
TimeUnit.SECONDS.sleep(10)
```

就可以避免發生以上的錯誤，不太確定是否因為 worker 還沒啟動完成就執行 PerfSource connector而造成錯誤，但是其它的 connector 都沒有此現象

**Comment by chia7712** [comment]
@jackyoh 請問一下 是每次都有這個錯誤嗎？我在我筆電試不出這個錯誤

**Comment by jackyoh** [comment]
對，每次都會錯。用 QA 環境也會出錯

**Comment by chia7712** [comment]
我測試了一下 的確是因為worker的http service還在啟動中因而遇到導致失敗

或許我們可以把相關的connector操作透過await來處理就好

**Comment by jackyoh** [comment]
我目前的想法是在 setupConnector 之前先 await connector list, await 完成之後在往下執行。

**Comment by chia7712** [comment]
> 我目前的想法是在 setupConnector 之前先 await connector list, await 完成之後在往下執行。

LGTM

**Comment by jackyoh** [comment]
使用 await connector list 還是有問題，像是 connector 還沒啟動時 list 會是 0. 所以沒有確實的 await 到。後來改成 await worker 的 plugins 不是空才往下執行。

**Comment by chia7712** [comment]
> 使用 await connector list 還是有問題，像是 connector 還沒啟動時 list 會是 0. 所以沒有確實的 await 到。

這部分的邏輯應該是等list不為0（也沒有錯誤）後才代表worker已經上線吧？

**Comment by jackyoh** [comment]
因為我是在 start 之前做 await 所以 list connector, 應該都會是 0。我先試著改寫上面說的方法，如果還不行，我就先用 await connector plugins
