### ISSUE TITLE
Gradle error: Process 'Gradle Test Executor XXX' finished with non-zero exit value 255

### ISSUE THREAD

**Issue by vitojeng** [oharastream/ohara#4014]
Gradle version: 5.6.3 / 5.6.4

I meet following message during ohara-configurator testing many times.
Some testing PASSED, but some testing occur this error. 

```
[ohara-configurator]$ gradle clean test -PskipManager
   :     :     :
com.island.ohara.configurator.TestConfiguratorBuilder > reassignK8sClient STARTED

com.island.ohara.configurator.TestConfiguratorBuilder > reassignK8sClient PASSED

com.island.ohara.configurator.TestConfiguratorBuilder > testK8SClientNamespaceNone STARTED

com.island.ohara.configurator.TestConfiguratorBuilder > testK8SClientNamespaceNone PASSED

com.island.ohara.configurator.TestConfiguratorBuilder > createFakeConfiguratorWithoutClusters STARTED
Process 'Gradle Test Executor 28' finished with non-zero exit value 255
This problem might be caused by incorrect test process configuration.
Please refer to the test execution section in the User Manual at https://docs.gradle.org/5.6.4/userguide/java_testing.html#sec:test_execution
org.gradle.process.internal.ExecException: Process 'Gradle Test Executor 28' finished with non-zero exit value 255
This problem might be caused by incorrect test process configuration.
Please refer to the test execution section in the User Manual at https://docs.gradle.org/5.6.4/userguide/java_testing.html#sec:test_execution
        at org.gradle.api.internal.tasks.testing.worker.ForkingTestClassProcessor.stop(ForkingTestClassProcessor.java:166)
        at org.gradle.api.internal.tasks.testing.processors.RestartEveryNTestClassProcessor.endBatch(RestartEveryNTestClassProcessor.java:77)
        at org.gradle.api.internal.tasks.testing.processors.RestartEveryNTestClassProcessor.processTestClass(RestartEveryNTestClassProcessor.java:55)
        at sun.reflect.GeneratedMethodAccessor147.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.dispatch.FailureHandlingDispatch.dispatch(FailureHandlingDispatch.java:30)
        at org.gradle.internal.dispatch.AsyncDispatch.dispatchMessages(AsyncDispatch.java:87)
        at org.gradle.internal.dispatch.AsyncDispatch.access$000(AsyncDispatch.java:36)
        at org.gradle.internal.dispatch.AsyncDispatch$1.run(AsyncDispatch.java:71)
        at org.gradle.internal.concurrent.InterruptibleRunnable.run(InterruptibleRunnable.java:42)
        at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:42)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
        at java.lang.Thread.run(Thread.java:748)
   :     :     :
   :     :     :
* What went wrong:
Execution failed for task ':ohara-configurator:test'.
> Process 'Gradle Test Executor 4' finished with non-zero exit value 255
  This problem might be caused by incorrect test process configuration.
  Please refer to the test execution section in the User Manual at https://docs.gradle.org/5.6.4/userguide/java_testing.html#sec:test_execution

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

Any thought?

**Comment by vitojeng** [comment]
The root cause is spray.json throw exception during ohara-configurator route initial phase in the **ShabondiRoute** :
```
Uncaught error from thread [Configurator-system-akka.actor.default-dispatcher-3]: null, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[Configurator-system]
java.lang.ExceptionInInitializerError
	at com.island.ohara.configurator.route.ShabondiRoute$.apply(ShabondiRoute.scala:169)
	at com.island.ohara.configurator.Configurator.$anonfun$basicRoute$1(Configurator.scala:268)
	at akka.http.scaladsl.server.Directive$.$anonfun$addByNameNullaryApply$2(Directive.scala:151)
	at akka.http.scaladsl.server.ConjunctionMagnet$$anon$2.$anonfun$apply$3(Directive.scala:219)
	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapInnerRoute$1(BasicDirectives.scala:39)
   :   :   :
   :   :   :
Caused by: java.lang.RuntimeException: Cannot automatically determine case class field names and order for 'com.island.ohara.client.configurator.v0.ShabondiApi$ShabondiClusterInfo', please use the 'jsonFormat' overload with explicit field name specification
	at spray.json.ProductFormats.extractFieldNames(ProductFormats.scala:86)
	at spray.json.ProductFormats.extractFieldNames$(ProductFormats.scala:68)
	at spray.json.DefaultJsonProtocol$.extractFieldNames(DefaultJsonProtocol.scala:30)
	at spray.json.ProductFormatsInstances.jsonFormat6(ProductFormatsInstances.scala:146)
	at spray.json.ProductFormatsInstances.jsonFormat6$(ProductFormatsInstances.scala:145)
	at spray.json.DefaultJsonProtocol$.jsonFormat6(DefaultJsonProtocol.scala:30)
	at com.island.ohara.client.configurator.v0.ShabondiApi$$anon$1.<init>(ShabondiApi.scala:91)
	at com.island.ohara.client.configurator.v0.ShabondiApi$.<init>(ShabondiApi.scala:90)
	at com.island.ohara.client.configurator.v0.ShabondiApi$.<clinit>(ShabondiApi.scala)
	... 42 more
Caused by: java.lang.RuntimeException: Case class com.island.ohara.client.configurator.v0.ShabondiApi$ShabondiClusterInfo declares additional fields
	at scala.sys.package$.error(package.scala:30)
	at spray.json.ProductFormats.extractFieldNames(ProductFormats.scala:80)
	... 50 more
```

Gradle error is gone after this exception fixed.
