### ISSUE TITLE
Manager crashed by an infinite loop

### ISSUE THREAD

**Issue by chuntsekevin** [oharastream/ohara#4091]
when click manager developer tool log(with data) and click back to topic will cause manager crash.
![image](https://user-images.githubusercontent.com/60953697/75021132-e29a9880-54ce-11ea-97b0-8042d3434198.png)

- [x] for 0.10 (#4102)
- [x] backport to 0.9 (#4108)

**Comment by chia7712** [comment]
ping @konekoya @wu87988622 @eechih @saivirtue

**Comment by chia7712** [comment]
@chuntsekevin Could you share the logs of Ohara Configurator to me? thanks!

**Comment by wu87988622** [comment]
@saivirtue look like #3992

**Comment by saivirtue** [comment]
I will take a look later.

**Comment by chuntsekevin** [comment]
@chia7712  
`Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at el (react-dom.production.min.js:214)
    at Object.enqueueForceUpdate (react-dom.production.min.js:134)
    at t.k.forceUpdate (react.production.min.js:13)
    at t.value (Grid.js:423)
    at t.value (Grid.js:954)
    at t.value (Grid.js:564)
    at yl (react-dom.production.min.js:251)
    at t.unstable_runWithPriority (scheduler.production.min.js:18)
    at Gr (react-dom.production.min.js:120)
    at bl (react-dom.production.min.js:244)
ds @ react-dom.production.min.js:196
Cs.a.payload @ react-dom.production.min.js:211
go @ react-dom.production.min.js:128
bo @ react-dom.production.min.js:129
Ji @ react-dom.production.min.js:178
As @ react-dom.production.min.js:261
ml @ react-dom.production.min.js:230
fl @ react-dom.production.min.js:229
ol @ react-dom.production.min.js:223
(anonymous) @ react-dom.production.min.js:121
t.unstable_runWithPriority @ scheduler.production.min.js:18
Gr @ react-dom.production.min.js:120
Jr @ react-dom.production.min.js:121
Zr @ react-dom.production.min.js:120
se @ react-dom.production.min.js:285
Ma @ react-dom.production.min.js:82`

**Comment by chia7712** [comment]
@chuntsekevin seems the error log is from Ohara Manager?

**Comment by chuntsekevin** [comment]
@chuntsekevin  yes this log is from manager , Chrome DevTools

**Comment by chia7712** [comment]
@chuntsekevin Could you use docker command ```docker logs ${your_configurator}``` to get the logs of Ohara Configurator?

**Comment by chia7712** [comment]
the logs is useful if the error is produced by Ohara Configurator

**Comment by chuntsekevin** [comment]
@chia7712 
sure !

`script: /home/ohara/ohara-configurator-0.9.0-SNAPSHOT/bin/start-service.sh
command-line arguments:  configurator --port 5000 --hostname node01
2020-02-21 05:50:06,797 INFO  [main] configurator.Configurator$(393): start a configurator built on hostname:node01 and port:5000
2020-02-21 05:50:06,800 INFO  [main] configurator.Configurator$(395): enter ctrl+c to terminate the configurator
2020-02-21 05:51:10,971 ERROR [pool-3-thread-4] configurator.Configurator$$anonfun$$nestedInanonfun$meterCache$1$1(170): failed to get metrics of service:{"group":"broker","name":"wk1"} from $anon$2
java.lang.IllegalArgumentException: java.io.IOException: Failed to retrieve RMIServer stub: javax.naming.CommunicationException [Root exception is java.rmi.ConnectIOException: error during JRMP connection establishment; nested exception is:
        java.net.SocketException: Connection reset]
        at oharastream.ohara.metrics.BeanChannel$Builder.doBuild(BeanChannel.java:321)
        at oharastream.ohara.metrics.BeanChannel$Builder.build(BeanChannel.java:329)
        at oharastream.ohara.agent.Collie.$anonfun$topicMeters$1(Collie.scala:251)
        at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:245)
        at scala.collection.immutable.Set$Set1.foreach(Set.scala:97)
        at scala.collection.TraversableLike.flatMap(TraversableLike.scala:245)
        at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:242)
        at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
        at oharastream.ohara.agent.Collie.topicMeters(Collie.scala:250)
        at oharastream.ohara.agent.Collie.topicMeters$(Collie.scala:248)
        at oharastream.ohara.agent.docker.BasicCollieImpl.topicMeters(BasicCollieImpl.scala:27)
        at oharastream.ohara.agent.Collie.$anonfun$counters$6(Collie.scala:301)
        at scala.util.Success.$anonfun$map$1(Try.scala:255)
        at scala.util.Success.map(Try.scala:213)
        at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Failed to retrieve RMIServer stub: javax.naming.CommunicationException [Root exception is java.rmi.ConnectIOException: error during JRMP connection establishment; nested exception is:
        java.net.SocketException: Connection reset]
        at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:369)
        at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270)
        at oharastream.ohara.metrics.BeanChannel$Builder.doBuild(BeanChannel.java:281)
        ... 20 more
Caused by: javax.naming.CommunicationException [Root exception is java.rmi.ConnectIOException: error during JRMP connection establishment; nested exception is:
        java.net.SocketException: Connection reset]
        at com.sun.jndi.rmi.registry.RegistryContext.lookup(RegistryContext.java:136)
        at com.sun.jndi.toolkit.url.GenericURLContext.lookup(GenericURLContext.java:205)
        at javax.naming.InitialContext.lookup(InitialContext.java:417)
        at javax.management.remote.rmi.RMIConnector.findRMIServerJNDI(RMIConnector.java:1955)
        at javax.management.remote.rmi.RMIConnector.findRMIServer(RMIConnector.java:1922)
        at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:287)
        ... 22 more
Caused by: java.rmi.ConnectIOException: error during JRMP connection establishment; nested exception is:
        java.net.SocketException: Connection reset
        at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:307)
        at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:202)
        at sun.rmi.server.UnicastRef.newCall(UnicastRef.java:343)
        at sun.rmi.registry.RegistryImpl_Stub.lookup(RegistryImpl_Stub.java:116)
        at com.sun.jndi.rmi.registry.RegistryContext.lookup(RegistryContext.java:132)
        ... 27 more
Caused by: java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:210)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
        at java.io.DataInputStream.readByte(DataInputStream.java:265)
        at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:246)
        ... 31 more
2020-02-21 05:53:23,175 ERROR [pool-3-thread-2] configurator.Configurator$$anonfun$exceptionHandler$1(136): Request to http://10.4.3.1:5000/v0/connectors/app1/start?group=2f87ead71 with HttpEntity.Strict(application/json,2 bytes total) is wrong
java.util.NoSuchElementException: {"group":"2f87ead71","name":"app1"} doesn't exist in oharastream.ohara.client.configurator.v0.ConnectorApi$ConnectorInfo
        at oharastream.ohara.configurator.store.RocksDataStore.$anonfun$value$2(RocksDataStore.scala:148)
        at scala.Option.getOrElse(Option.scala:189)
        at oharastream.ohara.configurator.store.RocksDataStore.$anonfun$value$1(RocksDataStore.scala:148)
        at scala.util.Success.$anonfun$map$1(Try.scala:255)
        at scala.util.Success.map(Try.scala:213)
        at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2020-02-21 08:24:30,523 ERROR [pool-3-thread-4] configurator.Configurator$$anonfun$exceptionHandler$1(136): Request to http://10.4.3.1:5000/v0/connectors/jout2/start?group=2f87ead71 with HttpEntity.Strict(application/json,2 bytes total) is wrong
java.lang.IllegalArgumentException: Connector configuration is invalid and contains the following 1 error(s):
Invalid value "56916" of type "java.lang.Integer" for configuration "jio.binding.port" :
Address already in use (Bind failed)
You can also find the above list of errors at the endpoint `/{connectorType}/config/validate`
        at oharastream.ohara.client.HttpExecutor$HttpExecutorImpl.$anonfun$asError$1(HttpExecutor.scala:164)
        at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
        at akka.http.scaladsl.util.FastFuture$.$anonfun$transformWith$1(FastFuture.scala:37)
        at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
        at akka.http.scaladsl.util.FastFuture$.transformWith$extension1(FastFuture.scala:45)
        at akka.http.scaladsl.util.FastFuture$.transformWith$extension0(FastFuture.scala:37)
        at akka.http.scaladsl.util.FastFuture$FulfilledFuture.transformWith(FastFuture.scala:86)
        at scala.concurrent.Future.flatMap(Future.scala:306)
        at scala.concurrent.Future.flatMap$(Future.scala:306)
        at akka.http.scaladsl.util.FastFuture$FulfilledFuture.flatMap(FastFuture.scala:77)
        at oharastream.ohara.client.HttpExecutor$HttpExecutorImpl.asError(HttpExecutor.scala:160)
        at oharastream.ohara.client.HttpExecutor$HttpExecutorImpl.unmarshal(HttpExecutor.scala:142)
        at oharastream.ohara.client.HttpExecutor$HttpExecutorImpl.$anonfun$post$2(HttpExecutor.scala:201)
        at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2020-02-21 08:24:34,391 ERROR [pool-3-thread-4] configurator.Configurator$$anonfun$exceptionHandler$1(136): Request to http://10.4.3.1:5000/v0/connectors/jout2/start?group=2f87ead71 with HttpEntity.Strict(application/json,2 bytes total) is wrong
java.lang.IllegalArgumentException: Connector configuration is invalid and contains the following 1 error(s):
Invalid value "56916" of type "java.lang.Integer" for configuration "jio.binding.port" :
Address already in use (Bind failed)
You can also find the above list of errors at the endpoint `/{connectorType}/config/validate`
        at oharastream.ohara.client.HttpExecutor$HttpExecutorImpl.$anonfun$asError$1(HttpExecutor.scala:164)
        at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
        at akka.http.scaladsl.util.FastFuture$.$anonfun$transformWith$1(FastFuture.scala:37)
        at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
        at akka.http.scaladsl.util.FastFuture$.transformWith$extension1(FastFuture.scala:45)
        at akka.http.scaladsl.util.FastFuture$.transformWith$extension0(FastFuture.scala:37)
        at akka.http.scaladsl.util.FastFuture$FulfilledFuture.transformWith(FastFuture.scala:86)
        at scala.concurrent.Future.flatMap(Future.scala:306)
        at scala.concurrent.Future.flatMap$(Future.scala:306)
        at akka.http.scaladsl.util.FastFuture$FulfilledFuture.flatMap(FastFuture.scala:77)
        at oharastream.ohara.client.HttpExecutor$HttpExecutorImpl.asError(HttpExecutor.scala:160)
        at oharastream.ohara.client.HttpExecutor$HttpExecutorImpl.unmarshal(HttpExecutor.scala:142)
        at oharastream.ohara.client.HttpExecutor$HttpExecutorImpl.$anonfun$post$2(HttpExecutor.scala:201)
        at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
`

**Comment by chuntsekevin** [comment]
@chia7712 
sure,


script: /home/ohara/ohara-configurator-0.9.0-SNAPSHOT/bin/start-service.sh
command-line arguments:  configurator --port 5000 --hostname node01
2020-02-21 05:50:06,797 INFO  [main] configurator.Configurator$(393): start a configurator built on hostname:node01 and port:5000
2020-02-21 05:50:06,800 INFO  [main] configurator.Configurator$(395): enter ctrl+c to terminate the configurator
2020-02-21 05:51:10,971 ERROR [pool-3-thread-4] configurator.Configurator$$anonfun$$nestedInanonfun$meterCache$1$1(170): failed to get metrics of service:{"group":"broker","name":"wk1"} from $anon$2
java.lang.IllegalArgumentException: java.io.IOException: Failed to retrieve RMIServer stub: javax.naming.CommunicationException [Root exception is java.rmi.ConnectIOException: error during JRMP connection establishment; nested exception is:
        java.net.SocketException: Connection reset]
        at oharastream.ohara.metrics.BeanChannel$Builder.doBuild(BeanChannel.java:321)
        at oharastream.ohara.metrics.BeanChannel$Builder.build(BeanChannel.java:329)
        at oharastream.ohara.agent.Collie.$anonfun$topicMeters$1(Collie.scala:251)
        at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:245)
        at scala.collection.immutable.Set$Set1.foreach(Set.scala:97)
        at scala.collection.TraversableLike.flatMap(TraversableLike.scala:245)
        at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:242)
        at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
        at oharastream.ohara.agent.Collie.topicMeters(Collie.scala:250)
        at oharastream.ohara.agent.Collie.topicMeters$(Collie.scala:248)
        at oharastream.ohara.agent.docker.BasicCollieImpl.topicMeters(BasicCollieImpl.scala:27)
        at oharastream.ohara.agent.Collie.$anonfun$counters$6(Collie.scala:301)
        at scala.util.Success.$anonfun$map$1(Try.scala:255)
        at scala.util.Success.map(Try.scala:213)
        at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Failed to retrieve RMIServer stub: javax.naming.CommunicationException [Root exception is java.rmi.ConnectIOException: error during JRMP connection establishment; nested exception is:
        java.net.SocketException: Connection reset]
        at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:369)
        at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270)
        at oharastream.ohara.metrics.BeanChannel$Builder.doBuild(BeanChannel.java:281)
        ... 20 more
Caused by: javax.naming.CommunicationException [Root exception is java.rmi.ConnectIOException: error during JRMP connection establishment; nested exception is:
        java.net.SocketException: Connection reset]
        at com.sun.jndi.rmi.registry.RegistryContext.lookup(RegistryContext.java:136)
        at com.sun.jndi.toolkit.url.GenericURLContext.lookup(GenericURLContext.java:205)
        at javax.naming.InitialContext.lookup(InitialContext.java:417)
        at javax.management.remote.rmi.RMIConnector.findRMIServerJNDI(RMIConnector.java:1955)
        at javax.management.remote.rmi.RMIConnector.findRMIServer(RMIConnector.java:1922)
        at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:287)
        ... 22 more
Caused by: java.rmi.ConnectIOException: error during JRMP connection establishment; nested exception is:
        java.net.SocketException: Connection reset
        at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:307)
        at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:202)
        at sun.rmi.server.UnicastRef.newCall(UnicastRef.java:343)
        at sun.rmi.registry.RegistryImpl_Stub.lookup(RegistryImpl_Stub.java:116)
        at com.sun.jndi.rmi.registry.RegistryContext.lookup(RegistryContext.java:132)
        ... 27 more
Caused by: java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:210)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
        at java.io.DataInputStream.readByte(DataInputStream.java:265)
        at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:246)
        ... 31 more
2020-02-21 05:53:23,175 ERROR [pool-3-thread-2] configurator.Configurator$$anonfun$exceptionHandler$1(136): Request to http://10.4.3.1:5000/v0/connectors/app1/start?group=2f87ead71 with HttpEntity.Strict(application/json,2 bytes total) is wrong
java.util.NoSuchElementException: {"group":"2f87ead71","name":"app1"} doesn't exist in oharastream.ohara.client.configurator.v0.ConnectorApi$ConnectorInfo
        at oharastream.ohara.configurator.store.RocksDataStore.$anonfun$value$2(RocksDataStore.scala:148)
        at scala.Option.getOrElse(Option.scala:189)
        at oharastream.ohara.configurator.store.RocksDataStore.$anonfun$value$1(RocksDataStore.scala:148)
        at scala.util.Success.$anonfun$map$1(Try.scala:255)
        at scala.util.Success.map(Try.scala:213)
        at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2020-02-21 08:24:30,523 ERROR [pool-3-thread-4] configurator.Configurator$$anonfun$exceptionHandler$1(136): Request to http://10.4.3.1:5000/v0/connectors/jout2/start?group=2f87ead71 with HttpEntity.Strict(application/json,2 bytes total) is wrong
java.lang.IllegalArgumentException: Connector configuration is invalid and contains the following 1 error(s):
Invalid value "56916" of type "java.lang.Integer" for configuration "jio.binding.port" :
Address already in use (Bind failed)
You can also find the above list of errors at the endpoint `/{connectorType}/config/validate`
        at oharastream.ohara.client.HttpExecutor$HttpExecutorImpl.$anonfun$asError$1(HttpExecutor.scala:164)
        at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
        at akka.http.scaladsl.util.FastFuture$.$anonfun$transformWith$1(FastFuture.scala:37)
        at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
        at akka.http.scaladsl.util.FastFuture$.transformWith$extension1(FastFuture.scala:45)
        at akka.http.scaladsl.util.FastFuture$.transformWith$extension0(FastFuture.scala:37)
        at akka.http.scaladsl.util.FastFuture$FulfilledFuture.transformWith(FastFuture.scala:86)
        at scala.concurrent.Future.flatMap(Future.scala:306)
        at scala.concurrent.Future.flatMap$(Future.scala:306)
        at akka.http.scaladsl.util.FastFuture$FulfilledFuture.flatMap(FastFuture.scala:77)
        at oharastream.ohara.client.HttpExecutor$HttpExecutorImpl.asError(HttpExecutor.scala:160)
        at oharastream.ohara.client.HttpExecutor$HttpExecutorImpl.unmarshal(HttpExecutor.scala:142)
        at oharastream.ohara.client.HttpExecutor$HttpExecutorImpl.$anonfun$post$2(HttpExecutor.scala:201)
        at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2020-02-21 08:24:34,391 ERROR [pool-3-thread-4] configurator.Configurator$$anonfun$exceptionHandler$1(136): Request to http://10.4.3.1:5000/v0/connectors/jout2/start?group=2f87ead71 with HttpEntity.Strict(application/json,2 bytes total) is wrong
java.lang.IllegalArgumentException: Connector configuration is invalid and contains the following 1 error(s):
Invalid value "56916" of type "java.lang.Integer" for configuration "jio.binding.port" :
Address already in use (Bind failed)
You can also find the above list of errors at the endpoint `/{connectorType}/config/validate`
        at oharastream.ohara.client.HttpExecutor$HttpExecutorImpl.$anonfun$asError$1(HttpExecutor.scala:164)
        at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
        at akka.http.scaladsl.util.FastFuture$.$anonfun$transformWith$1(FastFuture.scala:37)
        at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
        at akka.http.scaladsl.util.FastFuture$.transformWith$extension1(FastFuture.scala:45)
        at akka.http.scaladsl.util.FastFuture$.transformWith$extension0(FastFuture.scala:37)
        at akka.http.scaladsl.util.FastFuture$FulfilledFuture.transformWith(FastFuture.scala:86)
        at scala.concurrent.Future.flatMap(Future.scala:306)
        at scala.concurrent.Future.flatMap$(Future.scala:306)
        at akka.http.scaladsl.util.FastFuture$FulfilledFuture.flatMap(FastFuture.scala:77)
        at oharastream.ohara.client.HttpExecutor$HttpExecutorImpl.asError(HttpExecutor.scala:160)
        at oharastream.ohara.client.HttpExecutor$HttpExecutorImpl.unmarshal(HttpExecutor.scala:142)
        at oharastream.ohara.client.HttpExecutor$HttpExecutorImpl.$anonfun$post$2(HttpExecutor.scala:201)
        at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by saivirtue** [comment]
It's done.
Please help me to verify if the exception still existed :)

**Comment by chuntsekevin** [comment]
@saivirtue  Sorry, I pull the new image , it still happened 
![image](https://user-images.githubusercontent.com/60953697/75218676-cc921e00-57d5-11ea-9011-35ce5eac420e.png)

**Comment by saivirtue** [comment]
The latest commit was nearly 2 hours ago, maybe try to test this issue tomorrow?

**Comment by chuntsekevin** [comment]
@saivirtue Ok! Thanks

**Comment by saivirtue** [comment]
This issue had been resolved, close now.
