### ISSUE TITLE
Exactly once on official connectors

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#4457]
This issue is a umbrella ticket that we are going to go through all official connectors for the "exactly once" function.

The official connectors are shown below.

1. ftp connector
1. smb connector
1. hdfs connector
1. jdbc connector
1. json connector
1. perf connector
1. console connector

Except for json, perf and console connector, others connectors fetch/push data to external storage so we have to dig in to implement the "exactly once".

For another one, we need a chaos test for them to verify the "exactly once" also :)

The pull requests are listed below.

1. - [x] add exactly-once test for csv connector (ftp, smb and hdfs) (#4458)
1. - [x] add chaos test for jdbc connector (#4500)

**Comment by chia7712** [comment]
FYI @vitojeng

**Comment by vitojeng** [comment]
Cool~ Thanks @chia7712 !

**Comment by jackyoh** [comment]
我做完 issue #4439 之後，就會來做 description  第二項 jdbc 的部份

**Comment by jackyoh** [comment]
目前 jdbc source connector 在 exactly once 的測試程式，主要會增加以下幾個部份：

1. 在測試程式的 setup 開一個執行緒把資料一直寫入到資料庫, 寫入資料到一個時間點停止執行緒，例如 60 秒，在這個過程中測試程式會 start, pause 和 delete jdbc source connector。等最後要執行完測試之前確認 topic 的資料筆數是否和 rdb table 相等。

2. jdbc source connector 啟動時，在 rdb table 使用 SQL 指令去 insert, update 和 delete 資料表，確認 topic 的資料筆數是跟預期的一樣。

**Comment by chia7712** [comment]
@jackyoh 還要對資料做加加減減看是否會有重複的資料進topic

例如把一筆舊的資料刪掉然後再寫入一次之類的

**Comment by jackyoh** [comment]
ok, 這個部份我也會加入到測試裡面。

**Comment by vitojeng** [comment]
> 等最後要執行完測試之前確認 topic 的資料筆數是否和 rdb table 相等。

只確認資料筆數是否足夠?

**Comment by chia7712** [comment]
> 只確認資料筆數是否足夠?

比數和內容都要

**Comment by jackyoh** [comment]
> 只確認資料筆數是否足夠?

資料筆數跟資料內容都會確認

**Comment by chia7712** [comment]
@jackyoh 我剛剛測試jdbc的時候出現此錯誤

```
錯誤訊息
org.scalatest.exceptions.TestFailedException: 16853 was not equal to 16849
堆疊追蹤
org.scalatest.exceptions.TestFailedException: 16853 was not equal to 16849
	at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:343)
	at org.scalatest.Matchers$AnyShouldWrapper.shouldBe(Matchers.scala:6919)
	at oharastream.ohara.connector.jdbc.source.TestJDBCSourceConnectorExactlyOnce.testConnectorStartDelete(TestJDBCSourceConnectorExactlyOnce.scala:171)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

能否確認一下是否遇到data遺失?

**Comment by jackyoh** [comment]
因為目前我在我的 local 連續測試二次都沒噴錯誤，所以我想確認一下這是在 local 測的還是 QA 測到的錯誤
```
 gradle cleanTest ohara-connector:test --tests TestJDBCSourceConnectorExactlyOnce -PskipManager
```

**Comment by chia7712** [comment]
> 所以我想確認一下這是在 local 測的還是 QA 測到的錯誤

我先在QA看到，然後在local掛著一直跑也能噴出此錯誤

**Comment by jackyoh** [comment]
那可以給我 branch 名稱嗎？我想拉下來測看看，因為在我的環境跑還沒噴錯誤

**Comment by chia7712** [comment]
> 那可以給我 branch 名稱嗎？我想拉下來測看看，因為在我的環境跑還沒噴錯誤

跑master就可以了

**Comment by jackyoh** [comment]
OK, 我在測幾次看看。

**Comment by chia7712** [comment]
@jackyoh error again 

https://builds.is-land.com.tw/job/PreCommit-OHARA/9588/testReport/junit/oharastream.ohara.connector.jdbc.source/TestJDBCSourceConnectorExactlyOnce/testTableUpdate_1_test_input_data_time_is_30_000_MILLISECONDS_/

**Comment by jackyoh** [comment]
以上的錯誤訊息跟之前發生的錯誤原因有點不一樣，這次發生錯誤是在 update table 的地方，我會再查看看原因。另外我來開一個 issue 來紀錄 JDBC source connector 的 error 訊息, 來統計出錯的頻率和出錯的訊息，有助於之後再補測試程式和 debug 。

**Comment by chia7712** [comment]
@jackyoh 麻煩完成以下事項

1. 下個結論
1. 關閉此議題
1. 將後續的議題開好
1. 將此做為known issue放到0.10.0的release note (FYI @eechih )

**Comment by jackyoh** [comment]
ok, 我來下個結論。

在 0.10 版的 jdbc source connector 為了要做到讓資料 exactly once 寫了一些測試程式, 但不幸運的是目前測出來的結果還是有可能不是 exactly once，目前猜測主要的問題在 jdbc source connector recovery 這一段程式的 flag 和 offset 沒有控制好而導致資料筆數不正確，之後還會繼續撰寫測是程式來找出問題。

目前在 issue #4637 紀錄 jdbc source connector 的錯誤訊息，用來之後 debug 使用。
