### ISSUE TITLE
thrown IllegalArgumentException when Configurator startup

### ISSUE THREAD

**Issue by vitojeng** [oharastream/ohara#4509]
#4487 provide a great way to set up custom configurator for IT.
However, the configurator will be failed if the arg `ohara.it.configurator` passed.

```
Exception in thread "main" java.lang.IllegalArgumentException: input:--hostname 192.168.50.222 --port 58789 --folder /tmp/oharadev/home --k8s http://ohara00:8080/api/v1 --k8s-metrics-server http://ohara00:8080/apis --ohara.it.configurator 192.168.50.222:58789. [Usage] --folder --hostname --port --k8s --fake
	at oharastream.ohara.configurator.Configurator$.$anonfun$configurator$1(Configurator.scala:377)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at oharastream.ohara.configurator.Configurator$.configurator(Configurator.scala:366)
	at oharastream.ohara.configurator.Configurator$.main(Configurator.scala:396)
	at oharastream.ohara.configurator.Configurator.main(Configurator.scala)
```

ping @chia7712 , @jackyoh

**Comment by vitojeng** [comment]
Oh...it's my bad.
I should put this argument in another command...
