### ISSUE TITLE
JDBC source connector 測試程式執行失敗紀錄表

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara#4637]
目前 jdbc source connector 有寫了一些 Exactly once 的測試程式在 #4457, 但有時候執行測試程式的資料筆數會不正確，因此如果有發現此問題，再把 error 貼到以下 comment 裡，我會在建立漏掉的測試，來修改 jdbc source connector bug 的部份。

**Comment by jackyoh** [comment]
錯誤訊息
org.scalatest.exceptions.TestFailedException: 16853 was not equal to 16849
堆疊追蹤
org.scalatest.exceptions.TestFailedException: 16853 was not equal to 16849
	at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:343)
	at org.scalatest.Matchers$AnyShouldWrapper.shouldBe(Matchers.scala:6919)
	at oharastream.ohara.connector.jdbc.source.TestJDBCSourceConnectorExactlyOnce.testConnectorStartDelete(TestJDBCSourceConnectorExactlyOnce.scala:171)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)

**Comment by jackyoh** [comment]
測試程式的錯誤訊息：
```
org.scalatest.exceptions.TestFailedException: 14886 was not equal to 14887
	at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:343)
	at org.scalatest.Matchers$AnyShouldWrapper.shouldBe(Matchers.scala:6919)
	at oharastream.ohara.connector.jdbc.source.TestJDBCSourceConnectorExactlyOnce.testTableUpdate(TestJDBCSourceConnectorExactlyOnce.scala:265)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
```

```
2020-04-23 22:27:54,812 ERROR [controller-event-thread] utils.Logging(76): [Controller id=2 epoch=3] Controller 2 epoch 3 failed to change state for partition 2c582-5c925-0 from OfflinePartition to OnlinePartition
kafka.common.StateChangeFailedException: Failed to elect leader for partition 2c582-5c925-0 under strategy OfflinePartitionLeaderElectionStrategy(false)
	at kafka.controller.ZkPartitionStateMachine.$anonfun$doElectLeaderForPartitions$7(PartitionStateMachine.scala:427)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:553)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:551)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:920)
	at kafka.controller.ZkPartitionStateMachine.doElectLeaderForPartitions(PartitionStateMachine.scala:424)
	at kafka.controller.ZkPartitionStateMachine.electLeaderForPartitions(PartitionStateMachine.scala:335)
	at kafka.controller.ZkPartitionStateMachine.doHandleStateChanges(PartitionStateMachine.scala:236)
	at kafka.controller.ZkPartitionStateMachine.handleStateChanges(PartitionStateMachine.scala:157)
	at kafka.controller.PartitionStateMachine.triggerOnlineStateChangeForPartitions(PartitionStateMachine.scala:73)
	at kafka.controller.PartitionStateMachine.triggerOnlinePartitionStateChange(PartitionStateMachine.scala:58)
	at kafka.controller.PartitionStateMachine.startup(PartitionStateMachine.scala:41)
	at kafka.controller.KafkaController.onControllerFailover(KafkaController.scala:246)
	at kafka.controller.KafkaController.elect(KafkaController.scala:1344)
	at kafka.controller.KafkaController.processReelect(KafkaController.scala:1795)
	at kafka.controller.KafkaController.process(KafkaController.scala:1840)
```

**Comment by vitojeng** [comment]
> 目前 jdbc source connector 有寫了一些 Exactly once 的測試程式在 #4457, 但有時候執行測試程式的資料筆數會不正確

有機會在這個 milestone 修好嗎?

**Comment by jackyoh** [comment]
因為這些錯誤要測很多次才會出現，我還要在想一些 test case。所以有可能在這個 milestone 會修不好，如果有修好會先上 hot fix。
