### ISSUE TITLE
fix flaky TestApiUrl

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#4640]
```
錯誤訊息
java.io.IOException: Server returned HTTP response code: 403 for URL: https://ohara.readthedocs.io/en/latest/rest/index.html
堆疊追蹤
java.io.IOException: Server returned HTTP response code: 403 for URL: https://ohara.readthedocs.io/en/latest/rest/index.html
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
	at java.net.URL.openStream(URL.java:1068)
	at scala.io.Source$.fromURL(Source.scala:142)
	at scala.io.Source$.fromURL(Source.scala:132)
	at oharastream.ohara.configurator.route.TestApiUrl.testDocumentApiUrl(TestApiUrl.scala:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

Maybe we should use another way to get context from the URL.

**Comment by chia7712** [comment]
FYI @vitojeng @jackyoh

**Comment by vitojeng** [comment]
@chia7712 If you don't have enough time for this issue, I can take it.

**Comment by chia7712** [comment]
> If you don't have enough time for this issue, I can take it.

sure and thanks!
