### ISSUE TITLE
[Question] Docker Client 常出現 ssh client not started exception

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara#4918]
@chia7712 目前在跑 QA 時，會看到以下的錯誤訊息。我不太確定是 bug 還是說是因為 server network 或 I/O 太忙而出現的錯誤。

```
2020-05-18 04:37:43,486 ERROR [scala-execution-context-global-41] docker.DockerClient$$anon$1(235): failed to get container names from ohara-jenkins-it-10
java.lang.IllegalStateException: SshClient not started. Please call start() method before connecting to a server
	at org.apache.sshd.client.SshClient.doConnect(SshClient.java:587)
	at org.apache.sshd.client.SshClient.connect(SshClient.java:530)
	at org.apache.sshd.client.session.ClientSessionCreator.connect(ClientSessionCreator.java:134)
	at org.apache.sshd.client.session.ClientSessionCreator.connect(ClientSessionCreator.java:115)
	at org.apache.sshd.client.simple.AbstractSimpleClientSessionCreator$1.connect(AbstractSimpleClientSessionCreator.java:158)
	at org.apache.sshd.client.simple.AbstractSimpleClientSessionCreator.sessionLogin(AbstractSimpleClientSessionCreator.java:77)
	at org.apache.sshd.client.simple.SimpleSessionClient.sessionLogin(SimpleSessionClient.java:117)
	at org.apache.sshd.client.simple.SimpleSessionClient.sessionLogin(SimpleSessionClient.java:63)
	at oharastream.ohara.agent.Agent$Builder$$anon$1.execute(Agent.scala:123)
	at oharastream.ohara.agent.docker.DockerClient$$anon$1.$anonfun$containerNames$2(DockerClient.scala:209)
	at scala.collection.StrictOptimizedIterableOps.flatMap(StrictOptimizedIterableOps.scala:117)
	at scala.collection.StrictOptimizedIterableOps.flatMap$(StrictOptimizedIterableOps.scala:104)
	at scala.collection.immutable.ArraySeq.flatMap(ArraySeq.scala:35)
	at oharastream.ohara.agent.docker.DockerClient$$anon$1.$anonfun$containerNames$1(DockerClient.scala:207)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:430)
	at scala.concurrent.BatchingExecutor$AbstractBatch.runN(BatchingExecutor.scala:134)
	at scala.concurrent.BatchingExecutor$AsyncBatch.apply(BatchingExecutor.scala:163)
	at scala.concurrent.BatchingExecutor$AsyncBatch.apply(BatchingExecutor.scala:146)
	at scala.concurrent.BlockContext$.usingBlockContext(BlockContext.scala:107)
	at scala.concurrent.BatchingExecutor$AsyncBatch.run(BatchingExecutor.scala:154)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

詳細的連結：
https://builds.is-land.com.tw/job/PreCommit-OHARA/10031/testReport/junit/oharastream.ohara.it.collie/TestDockerClient/testRoute/

**Comment by chia7712** [comment]
@jackyoh 這個是ssh connection遇到錯誤後沒有重新初始化，#4563正在追蹤了

而此問題在很QA繁忙的時候比較容易出現，而目前在production使用上還沒遇過，所以我還沒合併該pr

**Comment by jackyoh** [comment]
了解，Thank you.

因為這個問題很像會導致  shabondi 跑測試的 container，無法刪除掉。使整合測試環境殘留一些 container, 但我目前還沒找到證據。
![2020-05-18 15-13-02 的螢幕擷圖](https://user-images.githubusercontent.com/15885064/82184408-3247ff00-991a-11ea-9837-0acf1ebc0ea5.png)

**Comment by jackyoh** [comment]
這個議題已經在 issue #4563 解決了，我先關閉此議題。
