### ISSUE TITLE
Fix flaky TestContainerClient.testVolume (k8s mode)

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#5234]
```
spray.json.DeserializationException: Object is missing required member 'nodeAffinity'
	at spray.json.package$.deserializationError(package.scala:23)
	at spray.json.ProductFormats.fromField(ProductFormats.scala:63)
	at spray.json.ProductFormats.fromField$(ProductFormats.scala:51)
	at spray.json.DefaultJsonProtocol$.fromField(DefaultJsonProtocol.scala:30)
	at spray.json.ProductFormatsInstances$$anon$1.read(ProductFormatsInstances.scala:37)
	at spray.json.ProductFormatsInstances$$anon$1.read(ProductFormatsInstances.scala:29)
	at akka.http.scaladsl.marshallers.sprayjson.SprayJsonSupport.$anonfun$sprayJsonUnmarshaller$1(SprayJsonSupport.scala:31)
	at akka.http.scaladsl.util.FastFuture$.$anonfun$map$1(FastFuture.scala:23)
	at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
	at akka.http.scaladsl.util.FastFuture$.transformWith$extension(FastFuture.scala:45)
	at akka.http.scaladsl.util.FastFuture$.map$extension(FastFuture.scala:23)
	at akka.http.scaladsl.unmarshalling.Unmarshaller.$anonfun$map$3(Unmarshaller.scala:26)
	at akka.http.scaladsl.unmarshalling.Unmarshaller.$anonfun$transform$3(Unmarshaller.scala:23)
	at akka.http.scaladsl.unmarshalling.Unmarshaller$$anon$1.apply(Unmarshaller.scala:58)
	at akka.http.scaladsl.unmarshalling.Unmarshal.to(Unmarshal.scala:25)
	at oharastream.ohara.client.HttpExecutor$HttpExecutorImpl.unmarshal(HttpExecutor.scala:141)
	at oharastream.ohara.client.HttpExecutor$HttpExecutorImpl.$anonfun$get$1(HttpExecutor.scala:179)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:433)
	at scala.concurrent.BatchingExecutor$AbstractBatch.runN(BatchingExecutor.scala:134)
	at scala.concurrent.BatchingExecutor$AsyncBatch.apply(BatchingExecutor.scala:163)
	at scala.concurrent.BatchingExecutor$AsyncBatch.apply(BatchingExecutor.scala:146)
	at scala.concurrent.BlockContext$.usingBlockContext(BlockContext.scala:107)
	at scala.concurrent.BatchingExecutor$AsyncBatch.run(BatchingExecutor.scala:154)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.util.NoSuchElementException: key not found: nodeAffinity
	at scala.collection.MapOps.default(Map.scala:245)
	at scala.collection.MapOps.default$(Map.scala:244)
	at scala.collection.AbstractMap.default(Map.scala:375)
	at scala.collection.MapOps.apply(Map.scala:147)
	at scala.collection.MapOps.apply$(Map.scala:146)
	at scala.collection.AbstractMap.apply(Map.scala:375)
	at spray.json.ProductFormats.fromField(ProductFormats.scala:58)
	at spray.json.ProductFormats.fromField$(ProductFormats.scala:51)
	at spray.json.DefaultJsonProtocol$.fromField(DefaultJsonProtocol.scala:30)
	at spray.json.ProductFormatsInstances$$anon$4.read(ProductFormatsInstances.scala:109)
	at spray.json.ProductFormatsInstances$$anon$4.read(ProductFormatsInstances.scala:95)
	at spray.json.ProductFormats.fromField(ProductFormats.scala:58)
	at spray.json.ProductFormats.fromField$(ProductFormats.scala:51)
	at spray.json.DefaultJsonProtocol$.fromField(DefaultJsonProtocol.scala:30)
	at spray.json.ProductFormatsInstances$$anon$2.read(ProductFormatsInstances.scala:59)
	at spray.json.ProductFormatsInstances$$anon$2.read(ProductFormatsInstances.scala:49)
	at spray.json.JsValue.convertTo(JsValue.scala:33)
	at spray.json.CollectionFormats$$anon$4.$anonfun$read$4(CollectionFormats.scala:91)
	at scala.collection.immutable.Vector1.map(Vector.scala:1810)
	at scala.collection.immutable.Vector1.map(Vector.scala:348)
	at spray.json.CollectionFormats$$anon$4.read(CollectionFormats.scala:91)
	at spray.json.CollectionFormats$$anon$4.read(CollectionFormats.scala:88)
	at spray.json.ProductFormats.fromField(ProductFormats.scala:58)
```

https://builds.is-land.com.tw/job/PreCommit-OHARA/10698/testReport/junit/oharastream.ohara.it.collie/TestContainerClient/testVolume_1_mode___K8S_/

**Comment by chia7712** [comment]
FYI @jackyoh

**Comment by jackyoh** [comment]
收到。有可能是測試程式的 bug，因為我在 local 上測試三次都是有同樣的錯誤。我再來修這個議題

**Comment by jackyoh** [comment]
我大概找到問題了，因為我星期三拿整合測試環境來 demo k8s 的 persistent volume, 當時是直接寫 yaml 檔，然後沒有寫 select 某一個 node, 因此使用 k8s volumes 的 api 撈 volume 資訊時就會沒有 nodeAffinity 的欄位資料。但是在 ohara 的 K8SClient 是假設都會有 nodeAffinity 欄位的 key，因此測試程式就會拋出錯誤。所以這是 k8s client 的 bug, nodeAffinity 應該要修改成 option。

目前因為還有其他 PR 在跑整合測試，因此暫時的解法是把之前建立的 persistent volume 刪除，讓整合測試能跑過。

**Comment by chia7712** [comment]
> 因此測試程式就會拋出錯誤。所以這是 k8s client 的 bug, nodeAffinity 應該要修改成 option。

聽起來可以先發隻PR改這部分？

**Comment by jackyoh** [comment]
可以先開 PR 來修改此問題。我先來改看看
