### ISSUE TITLE
[Question] ConnectorAdmin 是否能接受 settings 的 value 為空值（empty）

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara#5349]
目前在實作 jdbc source connector 有 timestamp mode 和 timestamp + increment mode 二種模式,  increment 的欄位 option 應該可以空值。但在建立 ConnectorAdmin 時會丟出 IllegalArgumentException 的 exception

程式碼如下：
```
val maps = Map(
  DB_URL                -> db.url,
  DB_USERNAME           -> db.user,
  DB_PASSWORD           -> db.password,
  DB_TABLENAME          -> tableName,
  TIMESTAMP_COLUMN_NAME -> timestampColumnName,
  INCREMENT_COLUMN_NAME -> "",
  TASK_TOTAL_KEY        -> "0",
  TASK_HASH_KEY         -> "0"
)

connectorAdmin
  .connectorCreator()
  .connectorKey(connectorKey)
  .connectorClass(classOf[JDBCSourceConnector])
  .topicKey(topicKey)
  .numberOfTasks(3)
  .settings(maps)
  .create()
```

錯誤訊息如下：
```
java.lang.IllegalArgumentException: it is illegal to assign empty/null value to key:source.timestamp.column.increment

	at oharastream.ohara.common.util.CommonUtils.requireNonEmpty(CommonUtils.java:400)
	at oharastream.ohara.kafka.connector.json.ConnectorFormatter.setting(ConnectorFormatter.java:103)
	at java.base/java.util.Map.forEach(Map.java:661)
	at oharastream.ohara.kafka.connector.json.ConnectorFormatter.settings(ConnectorFormatter.java:121)
	at oharastream.ohara.client.kafka.ConnectorAdmin$Creator.settings(ConnectorAdmin.scala:488)
	at oharastream.ohara.connector.jdbc.source.TestJDBCSourceConnector.testJDBCSourceConnector(TestJDBCSourceConnector.scala:109)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

丟錯誤的程式碼在 ConnectorFormatter#seting 第103行
```
CommonUtils.requireNonEmpty(
        value, () -> "it is illegal to assign empty/null value to key:" + key);
```

**Comment by chia7712** [comment]
> , increment 的欄位 option 應該可以空值

空字串是不合法的，合法的"空值"應該是沒有值，這也是definition中的optional的意義

**Comment by jackyoh** [comment]
> 空字串是不合法的

所以在以下的 map,  INCREMENT_COLUMN_NAME -> "" 是不合法的。
```
val maps = Map(
  DB_URL                -> db.url,
  DB_USERNAME           -> db.user,
  DB_PASSWORD           -> db.password,
  DB_TABLENAME          -> tableName,
  TIMESTAMP_COLUMN_NAME -> timestampColumnName,
  INCREMENT_COLUMN_NAME -> "",
  TASK_TOTAL_KEY        -> "0",
  TASK_HASH_KEY         -> "0"
)
```

> 合法的"空值"應該是沒有值

我有去試過，INCREMENT_COLUMN_NAME KEY 沒有定義也會收到 IllegalArgumentException 的 exception

**Comment by chia7712** [comment]
> 我有去試過，INCREMENT_COLUMN_NAME KEY

能否分享一下程式碼？

**Comment by jackyoh** [comment]
OK, 我來整理一下。

**Comment by jackyoh** [comment]
我發現是我的型態定義錯了，incrementColumnName 應該要用 Option[String] 而不是 String, 程式碼如下：

```
    JDBCSourceConnectorConfig(
      dbURL = settings.stringValue(DB_URL),
      dbUserName = settings.stringValue(DB_USERNAME),
      dbPassword = settings.stringValue(DB_PASSWORD),
      dbTableName = settings.stringValue(DB_TABLENAME),
      dbCatalogPattern = Option(settings.stringOption(DB_CATALOG_PATTERN).orElse(null)).filterNot(CommonUtils.isEmpty),
      dbSchemaPattern = Option(settings.stringOption(DB_SCHEMA_PATTERN).orElse(null)).filterNot(CommonUtils.isEmpty),
      mode = settings.stringOption(MODE).orElse(MODE_DEFAULT),
      jdbcFetchDataSize = settings.intOption(JDBC_FETCHDATA_SIZE).orElse(JDBC_FETCHDATA_SIZE_DEFAULT),
      jdbcFlushDataSize = settings.intOption(JDBC_FLUSHDATA_SIZE).orElse(JDBC_FLUSHDATA_SIZE_DEFAULT),
      jdbcFrequenceTime = Option(settings.durationOption(JDBC_FREQUENCE_TIME).orElse(null))
        .fold(JDBC_FREQUENCE_TIME_DEFAULT)(toScalaDuration),
      timestampColumnName = settings.stringValue(TIMESTAMP_COLUMN_NAME),
      incrementColumnName = Option(settings.stringOption(INCREMENT_COLUMN_NAME).orElse(null)).filterNot(CommonUtils.isEmpty)
    )
```

之前我把 incrementColumnName 寫成如下：

```
incrementColumnName = settings.stringOption(INCREMENT_COLUMN_NAME).orElse("")
```

**Comment by chia7712** [comment]
> 我發現是我的型態定義錯了

所以可以關閉議題了？

**Comment by jackyoh** [comment]
Ok, 我把此議題關閉。
