### ISSUE TITLE
Cannot run zookeeper with a volume

### ISSUE THREAD

**Issue by eechih** [oharastream/ohara#5435]
**To Reproduce**
1. Create and run a volume
```
{
    "group": "workspace1",
    "lastModified": 1594705145711,
    "name": "volume1",
    "nodeNames": [
        "ohara-dev-02"
    ],
    "path": "/home/ohara/data",
    "state": "RUNNING",
    "tags": {
        "displayName": "volume1"
    }
}
```

2. Create and run a zookeeper (`dataDir` type is `Volume`)
```
{
    "syncLimit": 5,
    "name": "workspace2",
    "state": "FAILED",
    "lastModified": 1594707079099,
    "electionPort": 38002,
    "xmx": 1024,
    "zookeeper.connection.timeout.ms": "10000 milliseconds",
    "imageName": "oharastream/zookeeper:0.11.0-SNAPSHOT",
    "aliveNodes": [],
    "initLimit": 10,
    "jmxPort": 38132,
    "xms": 1024,
    "routes": {},
    "dataDir": {
        "group": "workspace1",
        "name": "volume1"
    },
    "tags": {},
    "clientPort": 39792,
    "peerPort": 44232,
    "tickTime": 2000,
    "group": "zookeeper",
    "nodeNames": [
        "ohara-dev-02"
    ]
}
```

**Additional context**

Configurator log:
```
2020-07-14 05:51:34,147 [myid:] - ERROR [main:ZooKeeperServerMain@75] - Unable to access datadir, exiting abnormally
org.apache.zookeeper.server.persistence.FileTxnSnapLog$DatadirException: Unable to create data directory /tmp/zk_data/version-2
	at org.apache.zookeeper.server.persistence.FileTxnSnapLog.<init>(FileTxnSnapLog.java:127)
	at org.apache.zookeeper.server.ZooKeeperServerMain.runFromConfig(ZooKeeperServerMain.java:124)
	at org.apache.zookeeper.server.ZooKeeperServerMain.initializeAndRun(ZooKeeperServerMain.java:106)
	at org.apache.zookeeper.server.ZooKeeperServerMain.main(ZooKeeperServerMain.java:64)
	at org.apache.zookeeper.server.quorum.QuorumPeerMain.initializeAndRun(QuorumPeerMain.java:128)
	at org.apache.zookeeper.server.quorum.QuorumPeerMain.main(QuorumPeerMain.java:82)
Unable to access datadir, exiting abnormally
```

**Comment by eechih** [comment]
@chia7712 這個問題在 docker 和 k8s mode 都會發生 :(

**Comment by jackyoh** [comment]
我覺得要先確認 user name 為 ohara 並且 UID 要 1000, 才能建立 volume。確認 UID 指令如下：
```
# id -u ohara
```

**Comment by eechih** [comment]
> 我覺得要先確認 user name 為 ohara 並且 UID 要 1000, 才能建立 volume。確認 UID 指令如下：

```
[ohara@ohara-dev-02 data]$ id -u ohara
1001
```

@jackyoh 感謝 777 解惑

**Comment by eechih** [comment]
將 uid 改為 1000，這個問題就不會發生了。
