### ISSUE TITLE
exclude 426 error code when closing ftp inputstream

### ISSUE THREAD

**Issue by jackyoh** [oharastream/ohara#5587]
目前使用 0.11 的 ftp source connector 檔案大小約 6.3 MB。 檔案內容無法寫入到 topic，而是直接把檔案移到 error 的資料夾，錯誤訊息如下：

```
[2020-08-26 09:19:16,914] INFO [Worker clientId=connect-1, groupId=9cd5beb6a90143ceb25fa0b7d] Finished starting connectors and tasks (org.apache.kafka.connect.runtime.distributed.DistributedHerder:1236)
[2020-08-26 09:19:16,934] INFO WorkerSourceTask{id=fcfb6f54c-ftp-0} Source task finished initialization and start (org.apache.kafka.connect.runtime.WorkerSourceTask:233)
[2020-08-26 09:19:17,488] ERROR failed to handle /input/xxxx.csv (oharastream.ohara.kafka.connector.csv.source.CsvDataReader:75)
java.lang.IllegalStateException: Failed to complete pending command
	at oharastream.ohara.client.filesystem.ftp.FtpClient$Builder$FtpClientImpl$$anon$2.close(FtpClient.scala:352)
	at java.base/sun.nio.cs.StreamDecoder.implClose(StreamDecoder.java:378)
	at java.base/sun.nio.cs.StreamDecoder.close(StreamDecoder.java:193)
	at java.base/java.io.InputStreamReader.close(InputStreamReader.java:200)
	at java.base/java.io.BufferedReader.close(BufferedReader.java:528)
	at oharastream.ohara.kafka.connector.csv.source.CsvDataReader.read(CsvDataReader.java:69)
	at oharastream.ohara.kafka.connector.csv.CsvSourceTask.pollRecords(CsvSourceTask.java:90)
	at oharastream.ohara.kafka.connector.RowSourceTask.poll(RowSourceTask.java:178)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:289)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:256)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:185)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:235)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

使用 0.9 版本的 ftp source connector 能正常執行，把資料寫入到 topic 裡

- [x] 0.11.1 (#5614)
- [x] 0.12 (#5606)

**Comment by jackyoh** [comment]
這個議題有點重要，會影響 ftp source connector 的執行。因此我來 backport 回 0.11
