### ISSUE TITLE
Start zookeeper failed when enabling volume feature

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#5718]
**Describe the bug**
On my laptop, I've tried to create a workspace with volume feature. But start zookeeper will fail.

1. Create node in quickstart
2. enable volume
3. type `/tmp/test`
4. click next and validation passed

**Snapshot**
![image](https://user-images.githubusercontent.com/8088616/97414952-94804380-193f-11eb-9e6e-647a6c2ad017.png)

**Error message**
```json
{"code":"java.rmi.RemoteException","message":"receive error message: mkdir: can't create directory '/tmp/test/zookeeper': No such file or directory
; nested exception is: 
	java.rmi.RemoteException: Remote command failed (1): mkdir /tmp/test/zookeeper; nested exception is: 
	java.rmi.ServerException: 1","stack":"java.rmi.RemoteException: receive error message: mkdir: can't create directory '/tmp/test/zookeeper': No such file or directory
; nested exception is: 
	java.rmi.RemoteException: Remote command failed (1): mkdir /tmp/test/zookeeper; nested exception is: 
	java.rmi.ServerException: 1
	at oharastream.ohara.agent.Agent$Builder$$anon$1.execute(Agent.scala:186)
	at oharastream.ohara.agent.RemoteFolderHandler$$anon$1.$anonfun$create$1(RemoteFolderHandler.scala:93)
	at oharastream.ohara.agent.RemoteFolderHandler$$anon$1.$anonfun$create$1$adapted(RemoteFolderHandler.scala:91)
	at oharastream.ohara.agent.RemoteFolderHandler$$anon$1.$anonfun$agent$2(RemoteFolderHandler.scala:194)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:430)
	at scala.concurrent.BatchingExecutor$AbstractBatch.runN(BatchingExecutor.scala:134)
	at scala.concurrent.BatchingExecutor$AsyncBatch.apply(BatchingExecutor.scala:163)
	at scala.concurrent.BatchingExecutor$AsyncBatch.apply(BatchingExecutor.scala:146)
	at scala.concurrent.BlockContext$.usingBlockContext(BlockContext.scala:107)
	at scala.concurrent.BatchingExecutor$AsyncBatch.run(BatchingExecutor.scala:154)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.rmi.RemoteException: Remote command failed (1): mkdir /tmp/test/zookeeper; nested exception is: 
	java.rmi.ServerException: 1
	at org.apache.sshd.client.channel.ClientChannel.validateCommandExitStatusCode(ClientChannel.java:140)
	at org.apache.sshd.client.session.ClientSession.executeRemoteCommand(ClientSession.java:294)
	at oharastream.ohara.agent.Agent$Builder$$anon$1.execute(Agent.scala:182)
	... 15 more
Caused by: java.rmi.ServerException: 1
	... 18 more
"}
```

**Configurator info**
![image](https://user-images.githubusercontent.com/8088616/97415129-cbeef000-193f-11eb-9030-d4757fea6b88.png)

**Comment by saivirtue** [comment]
I've found the cause. It's because my configurator version is too old 😞
