### ISSUE TITLE
K8sClient.images doesn't show all images actually

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#827]
see [here](https://builds.is-land.com.tw/job/PreCommit-OHARA/1574/testReport/junit/com.island.ohara.it.agent.k8s/TestK8SClusterCollieByConfigurator/testZk/)

```java
java.lang.IllegalArgumentException: ohara-it-03 doesn't have docker image:oharastream/zookeeper:tmp_1574
	at com.island.ohara.client.HttpExecutor$HttpExecutorImpl.$anonfun$asError$1(HttpExecutor.scala:152)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at akka.http.scaladsl.util.FastFuture$.$anonfun$transformWith$1(FastFuture.scala:37)
	at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
	at akka.http.scaladsl.util.FastFuture$.transformWith$extension1(FastFuture.scala:45)
	at akka.http.scaladsl.util.FastFuture$.transformWith$extension0(FastFuture.scala:37)
	at akka.http.scaladsl.util.FastFuture$FulfilledFuture.transformWith(FastFuture.scala:86)
	at scala.concurrent.Future.flatMap(Future.scala:306)
	at scala.concurrent.Future.flatMap$(Future.scala:306)
	at akka.http.scaladsl.util.FastFuture$FulfilledFuture.flatMap(FastFuture.scala:77)
	at com.island.ohara.client.HttpExecutor$HttpExecutorImpl.asError(HttpExecutor.scala:148)
	at com.island.ohara.client.HttpExecutor$HttpExecutorImpl.unmarshal(HttpExecutor.scala:138)
	at com.island.ohara.client.HttpExecutor$HttpExecutorImpl.$anonfun$post$2(HttpExecutor.scala:183)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

```

**Comment by jackyoh** [comment]
我會去確認 k8s 的 api server  是否有撈到正確 docker image 數量

**Comment by chia7712** [comment]
```
      override def images(nodeName: String)(implicit executionContext: ExecutionContext): Future[Seq[String]] =
        Http().singleRequest(HttpRequest(HttpMethods.GET, uri = s"${k8sApiServerURL}/nodes/${nodeName}")).flatMap {
          response =>
            Unmarshal(response.entity).to[NodeItems] map { r =>
              r.status.images.filter(x => x.names.size >= 2).map(x => x.names.last)
            }
        }
```
the filter is useless and introduce this bug. see [k8s docs](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.14/#containerimage-v1-core) for it.

> 會去確認 k8s 的 api server 是否有撈到正確 docker image 數量

I will file a PR for this issue. Please take a look at the PR.

**Comment by jackyoh** [comment]
Ok, 我會去看 k8s API的說明
