### ISSUE TITLE
DataStore#exist() should return false if id not exist

### ISSUE THREAD

**Issue by vitojeng** [oharastream/ohara#864]
I expected DataStore#exist() should return `fasle` but throw exception instead.
Am I getting it wrong?

```text
java.util.NoSuchElementException: 54321 doesn't exist. total:7ae12,348b4,24901
	at com.island.ohara.configurator.store.Store$$anon$1.$anonfun$value$2(Store.scala:114)
	at scala.Option.getOrElse(Option.scala:138)
	at com.island.ohara.configurator.store.Store$$anon$1.value(Store.scala:113)
	at com.island.ohara.configurator.store.DataStore$DataStoreImpl.exist(DataStore.scala:105)
	at com.island.ohara.configurator.route.ShabondiRoute$.$anonfun$apply$6(ShabondiRoute.scala:75)
	at akka.http.scaladsl.server.Directive$.$anonfun$addByNameNullaryApply$2(Directive.scala:134)
```

**Comment by vitojeng** [comment]
The current implement:
```scala
    override def exist[T <: Data: ClassTag](id: String)(implicit executor: ExecutionContext): Future[Boolean] =
      store.value(id).map(classTag[T].runtimeClass.isInstance)
```

May should be(?) :
```scala
    override def exist[T <: Data: ClassTag](id: String)(implicit executor: ExecutionContext): Future[Boolean] =
      store.exist(id)
```

**Comment by chia7712** [comment]
> DataStore#exist()

It should return false instead of throwing exception.

```java
    override def exist[T <: Data: ClassTag](id: String)(implicit executor: ExecutionContext): Future[Boolean] =
      store.exist(id)
```

It needs to check the type also.
