### ISSUE TITLE
Fix flaky TestHDFSSinkConnector.testRunMiniClusterAndAssignConfig

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#878]
```java
java.lang.IllegalArgumentException: javax.management.InstanceAlreadyExistsException: com.island.ohara:name=row.counter,type=counter,group=testRunMiniClusterAndAssignConfig
	at com.island.ohara.metrics.BeanChannel$Register.run(BeanChannel.java:361)
	at com.island.ohara.metrics.basic.Counter$Builder.register(Counter.java:283)
	at com.island.ohara.kafka.connector.ConnectorUtils.rowCounter(ConnectorUtils.java:71)
	at com.island.ohara.kafka.connector.RowSinkTask.start(RowSinkTask.java:152)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:280)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:176)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.management.InstanceAlreadyExistsException: com.island.ohara:name=row.counter,type=counter,group=testRunMiniClusterAndAssignConfig
	at com.sun.jmx.mbeanserver.Repository.addMBean(Repository.java:437)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerWithRepository(DefaultMBeanServerInterceptor.java:1898)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerDynamicMBean(DefaultMBeanServerInterceptor.java:966)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:900)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:324)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
	at com.island.ohara.metrics.BeanChannel$Register.run(BeanChannel.java:355)
	... 12 more
```

It is caused by #776 which removed the id from java mbeans

**Comment by chia7712** [comment]
Oh...there is another root cause that ##841 auto-add the default value to input configs. The new behavior breaks the testRunMiniClusterAndAssignConfig
