### ISSUE TITLE
Fix flaky TestHDFSSinkConnector.testHDFSSinkConnector

### ISSUE THREAD

**Issue by chia7712** [oharastream/ohara#897]
see [here](https://builds.is-land.com.tw/job/PostCommit-OHARA/171/testReport/com.island.ohara.connector.hdfs/TestHDFSSinkConnector/testHDFSSinkConnector/)

```
錯誤訊息
java.lang.IllegalStateException: timeout
堆疊追蹤
java.lang.IllegalStateException: timeout
	at com.island.ohara.common.util.CommonUtils.await(CommonUtils.java:202)
	at com.island.ohara.common.util.CommonUtils.await(CommonUtils.java:170)
	at com.island.ohara.connector.hdfs.TestHDFSSinkConnector.testHDFSSinkConnector(TestHDFSSinkConnector.scala:151)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by chia7712** [comment]
ping @jackyoh

**Comment by chia7712** [comment]
I have started a loop test. see [here](https://builds.is-land.com.tw/job/PreTest-OHARA/347/console)

**Comment by jackyoh** [comment]
我有進去連結看, 測試有收到以下訊息：
```
12:23:00 Error: No such container: jenkins-PreTest-OHARA-347
12:23:00 Email was triggered for: Always
12:23:00 Sending email for trigger: Always
12:23:00 Sending email to: chia7712@gmail.com
12:23:02 Finished: SUCCESS
```
不太確定有沒有跑成功

**Comment by chia7712** [comment]
那個跟測試無關。你要看test reports

**Comment by jackyoh** [comment]
我看的 test reports 連結如下：
https://builds.is-land.com.tw/job/PreTest-OHARA/347/testReport/

測試有通過.

**Comment by chia7712** [comment]
Could you file a job with more loops? If it still pass, you can just close this issue.

**Comment by jackyoh** [comment]
OK, 我來測試.

**Comment by chia7712** [comment]
seems it is table now :)
