### ISSUE TITLE
[UT Test] Topic creation will always fail in get bean

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#922]
**Describe the bug**
When create topic via restful api, the request will get timeout and get connect exception in server part.

**To Reproduce**
1. run configurator via gradle command
`-Pport=1234 -Phostname=localhost -Pnode={node_information}`
2. pre create zk, bk cluster
3. create topic via api
3.1. url : **http://localhost:1234/vo/topics**, POST
3.2. request body 
```json
{
   "name": "fromTopic",
   "numberOfPartitions": 1,
   "numberOfReplications": 1
}
```

**Expected behavior**
create topic successful

**Error Stack Trace**
```
ava.lang.IllegalArgumentException: java.rmi.ConnectException: Connection refused to host: 172.17.0.3; nested exception is: 
	java.net.ConnectException: Connection timed out: connect
	at com.island.ohara.metrics.BeanChannel$Builder.doBuild(BeanChannel.java:309)
	at com.island.ohara.metrics.BeanChannel$Builder.build(BeanChannel.java:316)
	at com.island.ohara.agent.BrokerCollie.$anonfun$topicMeters$1(BrokerCollie.scala:57)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:244)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:244)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:241)
	at scala.collection.immutable.List.flatMap(List.scala:355)
	at com.island.ohara.agent.BrokerCollie.topicMeters(BrokerCollie.scala:56)
	at com.island.ohara.agent.BrokerCollie.topicMeters$(BrokerCollie.scala:56)
	at com.island.ohara.agent.ssh.BrokerCollieImpl.topicMeters(BrokerCollieImpl.scala:28)
```

**Comment by saivirtue** [comment]
ping @chia7712 
do you have any idea what's going on of this issue?

**Comment by chia7712** [comment]
#924 may resolve this issue.

**Comment by saivirtue** [comment]
hmm...already check firewall is disabled
![image](https://user-images.githubusercontent.com/8088616/56785433-c2a33580-6827-11e9-826d-96c0359c35a9.png)

BTW, I test the configurator by the version of two days before, and it seems OK

**Comment by chia7712** [comment]
> BTW, I test the configurator by the version of two days before, and it seems OK

thanks for the information. Please close this issue if the trouble is gone

**Comment by saivirtue** [comment]
problem not appear after update the broker image, close this issue
