### ISSUE TITLE
Fix flaky TestMetrics.testConnector

### ISSUE THREAD

**Issue by saivirtue** [oharastream/ohara#972]
See the trace message of QA :
```
java.lang.IllegalStateException: timeout
	at com.island.ohara.common.util.CommonUtils.await(CommonUtils.java:202)
	at com.island.ohara.common.util.CommonUtils.await(CommonUtils.java:170)
	at com.island.ohara.configurator.TestMetrics.assertNoMetricsForTopic(TestMetrics.scala:45)
	at com.island.ohara.configurator.TestMetrics.testConnector(TestMetrics.scala:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

see [here](https://github.com/oharastream/ohara/issues/972#issuecomment-488234620) for root cause

**Comment by saivirtue** [comment]
ping @chia7712 
do you ever encounter this error before?

**Comment by chia7712** [comment]
> do you ever encounter this error before?

not sure. Do you want to dig in it? I'm happy to take over it.

**Comment by saivirtue** [comment]
> not sure. Do you want to dig in it? I'm happy to take over it.

sure :)

**Comment by vitojeng** [comment]
> > do you ever encounter this error before?
> 
> not sure. Do you want to dig in it? I'm happy to take over it.

I am sure this error also occur in Shabondi related PR:
https://builds.is-land.com.tw/job/PreCommit-OHARA/1832/testReport/junit/com.island.ohara.configurator/TestMetrics/testConnector/

**Comment by chia7712** [comment]
the root cause is that the kafka may auto-create the topic deleted by this test if the connector has not been removed from worker. I will file a PR to fix this unstable test.
